{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"termList","items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"datadog trace"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTNetworkTraceTypeDDtrace"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"zipkin multi header"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTNetworkTraceTypeZipkinMultiHeader"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"zipkin single header"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTNetworkTraceTypeZipkinSingleHeader"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"w3c traceparent"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTNetworkTraceTypeTraceparent"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"skywalking 8.0+"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTNetworkTraceTypeSkywalking"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"jaeger"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTNetworkTraceTypeJaeger"}]}}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftnetworktracetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftnetworktracetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"网络链路追踪使用类型"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"}],"title":"FTNetworkTraceType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@FTNetworkTraceType","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceType"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/dDtrace","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/jaeger","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/skywalking","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/traceparent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinMultiHeader","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinSingleHeader"]},{"title":"Initializers","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/Equatable-Implementations","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/dDtrace":{"role":"symbol","title":"FTNetworkTraceType.dDtrace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dDtrace"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/dDtrace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeDDtrace"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/ddtrace"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/init(rawvalue:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/traceparent":{"role":"symbol","title":"FTNetworkTraceType.traceparent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"traceparent"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/traceparent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeTraceparent"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/traceparent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/skywalking":{"role":"symbol","title":"FTNetworkTraceType.skywalking","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"skywalking"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/skywalking","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeSkywalking"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/skywalking"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/rawrepresentable-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/equatable-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/jaeger":{"role":"symbol","title":"FTNetworkTraceType.jaeger","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jaeger"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/jaeger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeJaeger"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/jaeger"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/zipkinMultiHeader":{"role":"symbol","title":"FTNetworkTraceType.zipkinMultiHeader","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipkinMultiHeader"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinMultiHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinMultiHeader"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/zipkinmultiheader"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType":{"role":"symbol","title":"FTNetworkTraceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"}],"abstract":[{"type":"text","text":"网络链路追踪使用类型"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceType"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/zipkinSingleHeader":{"role":"symbol","title":"FTNetworkTraceType.zipkinSingleHeader","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipkinSingleHeader"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinSingleHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinSingleHeader"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/zipkinsingleheader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FTNetworkTraceType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTNetworkTraceType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/dDtrace","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/jaeger","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/skywalking","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/traceparent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinMultiHeader","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinSingleHeader"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1dDtrace\/title","value":"FTNetworkTraceTypeDDtrace"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1dDtrace\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeDDtrace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1traceparent\/title","value":"FTNetworkTraceTypeTraceparent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1traceparent\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeTraceparent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1skywalking\/title","value":"FTNetworkTraceTypeSkywalking"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1skywalking\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeSkywalking"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1jaeger\/title","value":"FTNetworkTraceTypeJaeger"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1jaeger\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeJaeger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1zipkinMultiHeader\/title","value":"FTNetworkTraceTypeZipkinMultiHeader"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1zipkinMultiHeader\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinMultiHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/title","value":"FTNetworkTraceType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1zipkinSingleHeader\/title","value":"FTNetworkTraceTypeZipkinSingleHeader"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1zipkinSingleHeader\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinSingleHeader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}