{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addResource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel","preciseIdentifier":"c:objc(cs)FTResourceMetricsModel","text":"FTResourceMetricsModel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","preciseIdentifier":"c:objc(cs)FTResourceContentModel","text":"FTResourceContentModel"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftexternalrum\/addresource(withkey:metrics:content:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftexternalrum\/addresource(withkey:metrics:content:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalRum\/addResource(withKey:metrics:content:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"请求数据"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"addResourceWithKey:metrics:content:"}],"role":"symbol","title":"addResource(withKey:metrics:content:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addResource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTResourceMetricsModel","preciseIdentifier":"c:objc(cs)FTResourceMetricsModel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTResourceContentModel","preciseIdentifier":"c:objc(cs)FTResourceContentModel"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)FTExternalRum(im)addResourceWithKey:metrics:content:","required":true,"modules":[{"name":"FTMobileAgent"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalRum"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalRum/addResource(withKey:metrics:content:)":{"navigatorTitle":[{"kind":"identifier","text":"addResourceWithKey:metrics:content:"}],"role":"symbol","title":"addResource(withKey:metrics:content:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addResource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTResourceMetricsModel","preciseIdentifier":"c:objc(cs)FTResourceMetricsModel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTResourceContentModel","preciseIdentifier":"c:objc(cs)FTResourceContentModel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"请求数据"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalRum\/addResource(withKey:metrics:content:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/ftmobileagent\/ftexternalrum\/addresource(withkey:metrics:content:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalRum":{"role":"symbol","title":"FTExternalRum","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTExternalRum"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalRum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTExternalRum"}],"url":"\/documentation\/ftmobileagent\/ftexternalrum"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel":{"role":"symbol","title":"FTResourceContentModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceContentModel"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceContentModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceMetricsModel":{"role":"symbol","title":"FTResourceMetricsModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceMetricsModel"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceMetricsModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcemetricsmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addResourceWithKey:metrics:content:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addResourceWithKey:metrics:content:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addResourceWithKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"metrics:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel","preciseIdentifier":"c:objc(cs)FTResourceMetricsModel","text":"FTResourceMetricsModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"metrics"},{"kind":"text","text":" "},{"kind":"identifier","text":"content:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","preciseIdentifier":"c:objc(cs)FTResourceContentModel","text":"FTResourceContentModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"content"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalRum~1addResource(withKey:metrics:content:)\/title","value":"addResourceWithKey:metrics:content:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalRum~1addResource(withKey:metrics:content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addResourceWithKey:metrics:content:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalRum\/title","value":"FTExternalRum"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalRum\/fragments","value":[{"kind":"identifier","text":"FTExternalRum"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel\/title","value":"FTResourceContentModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel\/fragments","value":[{"kind":"identifier","text":"FTResourceContentModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/title","value":"FTResourceMetricsModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/fragments","value":[{"kind":"identifier","text":"FTResourceMetricsModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}