{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"taskMetrics"},{"kind":"text","text":" "},{"kind":"internalParam","text":"metrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTaskMetrics","preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"metrics 实例."}]}]},{"kind":"parameters","parameters":[{"name":"metrics","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"SessionTaskMetric"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftresourcemetricsmodel\/init(taskmetrics:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftresourcemetricsmodel\/init(taskmetrics:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel\/init(taskMetrics:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"初始化方法"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithTaskMetrics:"}],"role":"symbol","title":"init(taskMetrics:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"taskMetrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTaskMetrics","preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:objc(cs)FTResourceMetricsModel(im)initWithTaskMetrics:","modules":[{"name":"FTMobileAgent"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceMetricsModel/init(taskMetrics:)":{"role":"symbol","title":"init(taskMetrics:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"taskMetrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTaskMetrics","preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"初始化方法"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel\/init(taskMetrics:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTaskMetrics:"}],"url":"\/documentation\/ftmobileagent\/ftresourcemetricsmodel\/init(taskmetrics:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceMetricsModel":{"role":"symbol","title":"FTResourceMetricsModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceMetricsModel"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceMetricsModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcemetricsmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"10.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithTaskMetrics:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTaskMetrics:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTaskMetrics:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLSessionTaskMetrics","preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"metrics"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel~1init(taskMetrics:)\/title","value":"initWithTaskMetrics:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel~1init(taskMetrics:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTaskMetrics:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/title","value":"FTResourceMetricsModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/fragments","value":[{"kind":"identifier","text":"FTResourceMetricsModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}