{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipkinMultiHeader"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftnetworktracetype\/zipkinmultiheader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftnetworktracetype\/zipkinmultiheader"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinMultiHeader","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"zipkin multi header"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipkinMultiHeader"}],"title":"FTNetworkTraceType.zipkinMultiHeader","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@FTNetworkTraceType@FTNetworkTraceTypeZipkinMultiHeader","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinMultiHeader"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType":{"role":"symbol","title":"FTNetworkTraceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"}],"abstract":[{"type":"text","text":"网络链路追踪使用类型"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceType"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType/zipkinMultiHeader":{"role":"symbol","title":"FTNetworkTraceType.zipkinMultiHeader","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zipkinMultiHeader"}],"abstract":[{"type":"text","text":"zipkin multi header"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType\/zipkinMultiHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinMultiHeader"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype\/zipkinmultiheader"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FTNetworkTraceTypeZipkinMultiHeader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinMultiHeader"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinMultiHeader"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/title","value":"FTNetworkTraceType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1zipkinMultiHeader\/title","value":"FTNetworkTraceTypeZipkinMultiHeader"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType~1zipkinMultiHeader\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceTypeZipkinMultiHeader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}