{"variants":[{"paths":["\/documentation\/ftmobileagent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"FTMobileAgent","title":"FTMobileAgent","symbolKind":"module","role":"collection","modules":[{"name":"FTMobileAgent"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/app-access","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/tutorials\/Meet-FTMobileSDK"]},{"title":"Classes","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"]},{"title":"Enumerations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType"]},{"title":"Model","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel"]},{"title":"Protocol","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding"]}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/tutorials/Meet-FTMobileSDK":{"role":"overview","title":"应用监测 配置教程","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/tutorials\/Meet-FTMobileSDK","kind":"overview","type":"topic","url":"\/tutorials\/meet-ftmobilesdk"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTTraceConfig":{"role":"symbol","title":"FTTraceConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTTraceConfig"}],"abstract":[{"type":"text","text":"Trace 功能配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTTraceConfig"}],"url":"\/documentation\/ftmobileagent\/fttraceconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel":{"role":"symbol","title":"FTResourceContentModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceContentModel"}],"abstract":[{"type":"text","text":"Resource 数据内容"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceContentModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency":{"role":"symbol","title":"FTMonitorFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMonitorFrequency"}],"abstract":[{"type":"text","text":"监控项采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus":{"role":"symbol","title":"FTLogStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogStatus"}],"abstract":[{"type":"text","text":"事件等级和状态，默认：FTStatusInfo"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLogStatus"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard":{"role":"symbol","title":"FTLogCacheDiscard","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogCacheDiscard"}],"abstract":[{"type":"text","text":"日志废弃策略"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLogCacheDiscard"}],"url":"\/documentation\/ftmobileagent\/ftlogcachediscard"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType":{"role":"symbol","title":"FTNetworkTraceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"}],"abstract":[{"type":"text","text":"网络链路追踪使用类型"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceType"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/app-access":{"role":"article","title":"iOS 应用接入","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/app-access","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/app-access"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceMetricsModel":{"role":"symbol","title":"FTResourceMetricsModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceMetricsModel"}],"abstract":[{"type":"text","text":"资源加载时间数据模型"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceMetricsModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcemetricsmodel"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig":{"role":"symbol","title":"FTRumConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"abstract":[{"type":"text","text":"RUM 功能的配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTRumConfig"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegate":{"role":"symbol","title":"FTURLSessionDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegate"}],"abstract":[{"type":"codeVoice","code":"URLSession"},{"type":"text","text":" 支持自动化采集的代理委托对象。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegate"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent":{"role":"symbol","title":"FTMobileAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"abstract":[{"type":"text","text":"FTMobileSDK"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileAgent"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegateProviding":{"role":"symbol","title":"FTURLSessionDelegateProviding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegateProviding"}],"abstract":[{"type":"text","text":"转发 ‘URLSessionDelegate’ 调用到 ‘ftURLSessionDelegate’的接口协议。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegateProviding"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegateproviding"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTTraceManager":{"role":"symbol","title":"FTTraceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTTraceManager"}],"abstract":[{"type":"text","text":"管理 trace 的类"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTTraceManager"}],"url":"\/documentation\/ftmobileagent\/fttracemanager"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLoggerConfig":{"role":"symbol","title":"FTLoggerConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLoggerConfig"}],"abstract":[{"type":"text","text":"logger 功能配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLoggerConfig"}],"url":"\/documentation\/ftmobileagent\/ftloggerconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType":{"role":"symbol","title":"FTDeviceMetricsMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"设备信息监控项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileConfig":{"role":"symbol","title":"FTMobileConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileConfig"}],"abstract":[{"type":"text","text":"SDK 基础配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileConfig"}],"url":"\/documentation\/ftmobileagent\/ftmobileconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager":{"role":"symbol","title":"FTExternalDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTExternalDataManager"}],"abstract":[{"type":"text","text":"实现用户自定义 RUM、 Trace 功能的类"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTExternalDataManager"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTErrorMonitorType":{"role":"symbol","title":"FTErrorMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTErrorMonitorType"}],"abstract":[{"type":"text","text":"ERROR 中的设备信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTErrorMonitorType"}],"url":"\/documentation\/ftmobileagent\/fterrormonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTEnv":{"role":"symbol","title":"FTEnv","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTEnv"}],"abstract":[{"type":"text","text":"环境字段。属性值：prod\/gray\/pre\/common\/local。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTEnv"}],"url":"\/documentation\/ftmobileagent\/ftenv"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/app-access","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/tutorials\/Meet-FTMobileSDK"]},{"title":"Classes","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"]},{"title":"Enumerations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType"]},{"title":"Model","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel"]},{"title":"Protocol","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceConfig\/title","value":"FTTraceConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceConfig\/fragments","value":[{"kind":"identifier","text":"FTTraceConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel\/title","value":"FTResourceContentModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel\/fragments","value":[{"kind":"identifier","text":"FTResourceContentModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/title","value":"FTMonitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus\/title","value":"FTLogStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus\/fragments","value":[{"kind":"identifier","text":"FTLogStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/title","value":"FTLogCacheDiscard"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/fragments","value":[{"kind":"identifier","text":"FTLogCacheDiscard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/title","value":"FTNetworkTraceType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/title","value":"FTResourceMetricsModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/fragments","value":[{"kind":"identifier","text":"FTResourceMetricsModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/title","value":"FTRumConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/fragments","value":[{"kind":"identifier","text":"FTRumConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/title","value":"FTURLSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/title","value":"FTMobileAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/fragments","value":[{"kind":"identifier","text":"FTMobileAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegateProviding\/title","value":"FTURLSessionDelegateProviding"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegateProviding\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegateProviding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceManager\/title","value":"FTTraceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceManager\/fragments","value":[{"kind":"identifier","text":"FTTraceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/title","value":"FTLoggerConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/fragments","value":[{"kind":"identifier","text":"FTLoggerConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/title","value":"FTDeviceMetricsMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileConfig\/title","value":"FTMobileConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileConfig\/fragments","value":[{"kind":"identifier","text":"FTMobileConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/title","value":"FTExternalDataManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/fragments","value":[{"kind":"identifier","text":"FTExternalDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/title","value":"FTErrorMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/fragments","value":[{"kind":"identifier","text":"FTErrorMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTEnv\/title","value":"FTEnv"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTEnv\/fragments","value":[{"kind":"identifier","text":"FTEnv"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}