{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceMetricsMonitorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType","text":"FTDeviceMetricsMonitorType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftrumconfig\/devicemetricsmonitortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftrumconfig\/devicemetricsmonitortype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/deviceMetricsMonitorType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"设置监控类型 不设置则不开启监控"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceMetricsMonitorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType"}],"title":"deviceMetricsMonitorType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)FTRumConfig(py)deviceMetricsMonitorType","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"deviceMetricsMonitorType"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/deviceMetricsMonitorType":{"role":"symbol","title":"deviceMetricsMonitorType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceMetricsMonitorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"设置监控类型 不设置则不开启监控"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/deviceMetricsMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceMetricsMonitorType"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/devicemetricsmonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType":{"role":"symbol","title":"FTDeviceMetricsMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"监控项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig":{"role":"symbol","title":"FTRumConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTRumConfig"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"deviceMetricsMonitorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deviceMetricsMonitorType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType","text":"FTDeviceMetricsMonitorType"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceMetricsMonitorType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1deviceMetricsMonitorType\/title","value":"deviceMetricsMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1deviceMetricsMonitorType\/fragments","value":[{"kind":"identifier","text":"deviceMetricsMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/title","value":"FTDeviceMetricsMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/title","value":"FTRumConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/fragments","value":[{"kind":"identifier","text":"FTRumConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}