{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","preciseIdentifier":"c:@E@FTMonitorFrequency","text":"FTMonitorFrequency"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftrumconfig\/monitorfrequency"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftrumconfig\/monitorfrequency"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/monitorFrequency","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"设置监控采样周期"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTMonitorFrequency","preciseIdentifier":"c:@E@FTMonitorFrequency"}],"title":"monitorFrequency","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)FTRumConfig(py)monitorFrequency","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"monitorFrequency"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig":{"role":"symbol","title":"FTRumConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"abstract":[{"type":"text","text":"RUM 功能的配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTRumConfig"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency":{"role":"symbol","title":"FTMonitorFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMonitorFrequency"}],"abstract":[{"type":"text","text":"监控项采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/monitorFrequency":{"role":"symbol","title":"monitorFrequency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTMonitorFrequency","preciseIdentifier":"c:@E@FTMonitorFrequency"}],"abstract":[{"type":"text","text":"设置监控采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/monitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"monitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/monitorfrequency"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"monitorFrequency"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"monitorFrequency"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","preciseIdentifier":"c:@E@FTMonitorFrequency","text":"FTMonitorFrequency"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorFrequency"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/title","value":"FTRumConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/fragments","value":[{"kind":"identifier","text":"FTRumConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/title","value":"FTMonitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1monitorFrequency\/title","value":"monitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1monitorFrequency\/fragments","value":[{"kind":"identifier","text":"monitorFrequency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}