{"primaryContentSections":[{"kind":"content","content":[{"anchor":"简介","level":2,"type":"heading","text":"简介"},{"type":"paragraph","inlineContent":[{"type":"text","text":"“观测云” 应用监测能够通过收集各个iOS应用的指标数据，以可视化的方式分析各个iOS应用端的性能。"}]},{"anchor":"前置条件","level":2,"type":"heading","text":"前置条件"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"安装 DataKit（"},{"type":"reference","isActive":true,"identifier":"..\/..\/datakit\/datakit-install.md"},{"type":"text","text":"）"}]}]}]},{"anchor":"iOS应用接入","level":2,"type":"heading","text":"iOS应用接入"},{"type":"paragraph","inlineContent":[{"type":"text","text":"登录观测云控制台，进入「用户访问监测」页面，点击右上角「新建应用」，在新窗口输入「应用名称」并自定义「应用 ID 标识」，点击「创建」，即可选择应用类型获取接入方式。"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"应用名称（必填项）：用于识别当前实施用户访问监测的应用名称。"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"应用 ID（必填项）：应用在当前工作空间的唯一标识，用于 SDK 采集数据上传匹配，数据入库后对应字段：app_id 。该字段仅支持英文、数字、下划线输入，最多为 48 个字符。"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"13.rum_access_3.png"}]},{"anchor":"安装","level":2,"type":"heading","text":"安装"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"https:\/\/img.shields.io\/cocoapods\/p\/FTMobileAgent#crop=0&crop=0&crop=1&crop=1&id=xs5E2&originHeight=20&originWidth=82&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title="},{"type":"image","identifier":"https:\/\/img.shields.io\/cocoapods\/v\/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=Uyl38&originHeight=20&originWidth=122&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title="},{"type":"image","identifier":"https:\/\/img.shields.io\/cocoapods\/l\/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=SxRum&originHeight=20&originWidth=98&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title="},{"type":"image","identifier":"https:\/\/img.shields.io\/badge\/iOS-api >= iOS 10-brightgreen#crop=0&crop=0&crop=1&crop=1&id=uFhFJ&originHeight=20&originWidth=118&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title="}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Demo"}]},{"type":"text","text":"："},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/tree\/develop\/demo"}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"源码地址"}]},{"type":"text","text":"："},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/GuanceCloud\/datakit-ios"}]},{"anchor":"源码方式","level":3,"type":"heading","text":"源码方式"},{"type":"paragraph","inlineContent":[{"type":"text","text":"1.从 GitHub 获取 SDK 的源代码。"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"2.将 SDK 源代码导入 App 项目，并选中 "},{"type":"codeVoice","code":"Copy items if needed"},{"type":"text","text":"。直接将 "},{"type":"strong","inlineContent":[{"type":"text","text":"FTMobileSDK"}]},{"type":"text","text":" 整个文件夹导入项目。"}]},{"anchor":"CocoaPods-方式","level":3,"type":"heading","text":"CocoaPods 方式"},{"type":"paragraph","inlineContent":[{"type":"text","text":"1.配置 "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":" 文件。"}]},{"type":"codeListing","syntax":"objectivec","code":["target 'yourProjectName' do","","# Pods for your project","pod 'FTMobileSDK', '1.3.8-beta.2'","    ","end"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"2.在 "},{"type":"codeVoice","code":"Podfile"},{"type":"text","text":" 目录下执行 "},{"type":"codeVoice","code":"pod install"},{"type":"text","text":" 安装 SDK。"}]},{"anchor":"Carthage-方式","level":3,"type":"heading","text":"Carthage 方式"},{"type":"paragraph","inlineContent":[{"type":"text","text":"1.配置 "},{"type":"codeVoice","code":"Cartfile"},{"type":"text","text":" 文件。"}]},{"type":"codeListing","syntax":null,"code":["github \"GuanceCloud\/datakit-ios\" == 1.3.8-beta.2"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"2.在 "},{"type":"codeVoice","code":"Cartfile"},{"type":"text","text":" 目录下执行  "},{"type":"codeVoice","code":"carthage update --platform iOS"},{"type":"text","text":" ， 并将  "},{"type":"codeVoice","code":"FTMobileSDK.framework"},{"type":"text","text":" 拖拽到您的项目中使用。若出现 “Building universal frameworks with common architectures is not possible. The device and simulator slices for “FTMobileSDK.framework” both build for: arm64” 错误，请执行  "},{"type":"codeVoice","code":"carthage update --platform iOS --use-xcframeworks"},{"type":"text","text":" 命令，生成  "},{"type":"codeVoice","code":"FTMobileSDK.xcframework "},{"type":"text","text":"，与普通的 Framework 使用方法相同，请将它拖拽到您的项目中使用。"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"3.debug 模式下，为了方便 SDK 调试，建议使用 debug 模式的静态库。在命令后添加  "},{"type":"codeVoice","code":"--configuration Debug"},{"type":"text","text":" 获取 debug 模式的静态库。"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"4.在 "},{"type":"codeVoice","code":"TARGETS"},{"type":"text","text":"  -> "},{"type":"codeVoice","code":"Build Setting"},{"type":"text","text":" ->  "},{"type":"codeVoice","code":"Other Linker Flags"},{"type":"text","text":"  添加  "},{"type":"codeVoice","code":"-ObjC"},{"type":"text","text":"。"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"5.目前只支持 1.3.4-beta.2 及以上的版本。"}]},{"anchor":"添加头文件","level":3,"type":"heading","text":"添加头文件"},{"type":"codeListing","syntax":"objectivec","code":["\/\/使用 Carthage 方式","#import <FTMobileAgent\/FTMobileAgent.h>","...","\/\/使用 源码 或 CocoaPods 方式","#import \"FTMobileAgent.h\""]},{"anchor":"SDK-初始化","level":2,"type":"heading","text":"SDK 初始化"},{"anchor":"基础配置","level":3,"type":"heading","text":"基础配置"},{"type":"codeListing","syntax":"objectivec","code":["-(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions{","    \/\/ SDK FTMobileConfig 设置","    FTMobileConfig *config = [[FTMobileConfig alloc]initWithMetricsUrl:@\"Your App metricsUrl\"];","    config.enableSDKDebugLog = YES;","    \/\/启动 SDK","    [FTMobileAgent startWithConfigOptions:config];","    ","   \/\/...","    return YES;","}"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"字段"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"类型"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"说明"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"必须"}]}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"metricsUrl"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSString"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"数据上报地址"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"是"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableSDKDebugLog"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置是否允许打印日志"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"env"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NS_ENUM"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"环境"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否  （默认FTEnvProd）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"XDataKitUUID"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSString"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"请求HTTP请求头X-Datakit-UUID 数据采集端  如果用户不设置会自动配置"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"globalContext"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSDictionary"}]}],[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"#user-global-context"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否"}]}]]],"header":"row"},{"anchor":"env-环境","level":4,"type":"heading","text":"env 环境"},{"type":"codeListing","syntax":"objectivec","code":["typedef NS_ENUM(NSInteger, FTEnv) {","    FTEnvProd         = 0, \/\/线上环境","    FTEnvGray,             \/\/灰度环境","    FTEnvPre,              \/\/预发布环境","    FTEnvCommon,           \/\/日常环境","    FTEnvLocal,            \/\/本地环境","};","","@property (nonatomic, assign) FTEnv env;"]},{"anchor":"RUM-配置","level":3,"type":"heading","text":"RUM 配置"},{"type":"codeListing","syntax":"objectivec","code":["    \/\/开启 rum","    FTRumConfig *rumConfig = [[FTRumConfig alloc]init];","    rumConfig.appid = appid;","    rumConfig.enableTrackAppCrash = YES;","    rumConfig.enableTrackAppANR = YES;","    rumConfig.enableTrackAppFreeze = YES;","    rumConfig.enableTraceUserAction = YES;","\t  rumConfig.enableTraceUserVIew = YES;","    rumConfig.deviceMetricsMonitorType = FTDeviceMetricsMonitorAll;","    [[FTMobileAgent sharedInstance] startRumWithConfigOptions:rumConfig];"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"字段"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"类型"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"说明"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"必须"}]}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"appid"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSString"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"DataFlux rum应用唯一ID标识，在DataFlux控制台上面创建监控时自动生成。"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（开启RUM 必选）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"samplerate"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"int"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"采样采集率"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认100）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"errorMonitorType"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NS_OPTIONS"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"error数据中的采集数据"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableTrackAppCrash"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置是否需要采集崩溃日志"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableTrackAppANR"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"采集ANR卡顿无响应事件"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableTrackAppFreeze"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"采集UI卡顿事件"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableTraceUserAction"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置是否追踪用户 Action 操作"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableTraceUserView"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置是否追踪用户 View 操作"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"globalContext"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSDictionary"}]}],[{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"添加自定义标签"}],"isActive":true,"type":"reference","identifier":"#user-global-context","overridingTitle":"添加自定义标签"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"deviceMetricsMonitorType"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NS_OPTIONS"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"监控类型"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（未设置则不开启监控）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"monitorFrequency"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NS_OPTIONS"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置监控采样周期"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否"}]}]]],"header":"row"},{"anchor":"监控数据配置","level":4,"type":"heading","text":"监控数据配置"},{"type":"paragraph","inlineContent":[{"type":"text","text":"配置 "},{"type":"codeVoice","code":"FTRumConfig"},{"type":"text","text":" 的 "},{"type":"codeVoice","code":"errorMonitorType"},{"type":"text","text":" 属性，将在采集的崩溃数据中添加对应的信息。可采集的类型如下："}]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," *"," * @constant"," *  FTMonitorInfoTypeBattery  - 电池电量"," *  FTMonitorInfoTypeMemory   - 内存总量、内存使用率"," *  FTMonitorInfoTypeCpu      - CPU使用率"," *\/","typedef NS_OPTIONS(NSUInteger, FTMonitorInfoType) {","    FTMonitorInfoTypeAll          = 0xFFFFFFFF,","    FTMonitorInfoTypeBattery      = 1 << 1,","    FTMonitorInfoTypeMemory       = 1 << 2,","    FTMonitorInfoTypeCpu          = 1 << 3,","};"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"配置 "},{"type":"codeVoice","code":"FTRumConfig"},{"type":"text","text":" 的 "},{"type":"codeVoice","code":"deviceMetricsMonitorType"},{"type":"text","text":" 属性，将在采集的  "},{"type":"strong","inlineContent":[{"type":"text","text":"View"}]},{"type":"text","text":" 数据中添加对应监控项信息，同时可配置 "},{"type":"codeVoice","code":"monitorFrequency"},{"type":"text","text":" 来设置监控采样周期。可采集的类型与采样周期如下："}]},{"type":"codeListing","syntax":"objective-c","code":["\/**"," * 监控项"," * @constant"," *  FTDeviceMetricsMonitorMemory   - 平均内存、最高内存"," *  FTDeviceMetricsMonitorCpu      - CPU跳动最大、平均数"," *  FTDeviceMetricsMonitorFps      - fps 最低帧率、平均帧率"," *\/","typedef NS_OPTIONS(NSUInteger, FTDeviceMetricsMonitorType){","    FTDeviceMetricsMonitorAll      = 0xFFFFFFFF,","    FTDeviceMetricsMonitorCpu      = 1 << 1,","    FTDeviceMetricsMonitorMemory   = 1 << 2,","    FTDeviceMetricsMonitorFps      = 1 << 3,","};","","\/**"," * 监控项采样周期"," * @constant"," *  FTMonitorFrequencyDefault   - 500ms (默认)"," *  FTMonitorFrequencyFrequent  - 100ms"," *  FTMonitorFrequencyRare      - 1000ms"," *\/","typedef NS_OPTIONS(NSUInteger, FTMonitorFrequency) {","    FTMonitorFrequencyDefault,","    FTMonitorFrequencyFrequent,","    FTMonitorFrequencyRare,","};"]},{"anchor":"Log-配置","level":3,"type":"heading","text":"Log 配置"},{"type":"codeListing","syntax":"objectivec","code":["    \/\/开启 logger","    FTLoggerConfig *loggerConfig = [[FTLoggerConfig alloc]init];","    loggerConfig.enableCustomLog = YES;","    loggerConfig.enableLinkRumData = YES;","    loggerConfig.enableConsoleLog = YES;","    [[FTMobileAgent sharedInstance] startLoggerWithConfigOptions:loggerConfig];","    "]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"字段"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"类型"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"说明"}]}]}],[{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"必须"}]}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"samplerate"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"int"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"采样采集率"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认100）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"serviceName"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSString"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置日志所属业务或服务的名称"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认df_rum_ios）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableConsoleLog"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置是否需要采集控制台日志"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"prefix"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSString"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置采集控制台日志过滤字符串"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认全采集）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableCustomLog"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"是否上传自定义 log"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"logLevelFilter"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSArray"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置要采集的自定义 log 的状态数组"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认全采集）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableLinkRumData"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"是否将 logger 数据与 rum 关联"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"discardType"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"FTLogCacheDiscard"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置日志废弃策略"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认丢弃最新数据）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"globalContext"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSDictionary"}]}],[{"type":"paragraph","inlineContent":[{"overridingTitleInlineContent":[{"type":"text","text":"添加自定义标签"}],"isActive":true,"type":"reference","identifier":"#user-global-context","overridingTitle":"添加自定义标签"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否"}]}]]],"header":"row"},{"anchor":"日志废弃策略","level":4,"type":"heading","text":"日志废弃策略"},{"type":"codeListing","syntax":"objectivec","code":["typedef NS_ENUM(NSInteger, FTLogCacheDiscard)  {","    FTDiscard,        \/\/默认，当日志数据数量大于最大值（5000）时，新数据不进行写入","    FTDiscardOldest   \/\/当日志数据数量大于最大值时,废弃旧数据","};","","\/**"," * 设置日志废弃策略"," *\/","@property (nonatomic, assign) FTLogCacheDiscard  discardType;"]},{"anchor":"采集控制台日志","level":4,"type":"heading","text":"采集控制台日志"},{"type":"paragraph","inlineContent":[{"type":"text","text":"一般情况下， 因为 NSLog 的输出会消耗系统资源，而且输出的数据也可能会暴露出App里的保密数据， 所以在发布正式版时会把这些输出全部屏蔽掉。此时开启采集控制台日志，也并不能抓取到工程里打印的日志。建议使用 "},{"type":"reference","isActive":true,"identifier":"#user-logger"},{"type":"text","text":" 来上传想查看的日志。"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"开启采集控制台日志"}]}]}]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," *设置是否需要采集控制台日志 默认为NO"," *\/"," @property (nonatomic, assign) BOOL enableConsoleLog;"]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置采集控制台日志的过滤条件"}]}]}]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * 设置采集控制台日志过滤字符串 包含该字符串控制台日志会被采集 默认为全采集"," *\/","@property (nonatomic, copy) NSString *prefix;"]},{"anchor":"Trace-配置","level":2,"type":"heading","text":"Trace 配置"},{"type":"codeListing","syntax":"objectivec","code":["    \/\/开启 trace","    FTTraceConfig *traceConfig = [[FTTraceConfig alloc]init];","    traceConfig.enableLinkRumData = YES;","\t  traceConfig.enableAutoTrace = YES;","    traceConfig.networkTraceType = FTNetworkTraceTypeDDtrace;","    [[FTMobileAgent sharedInstance] startTraceWithConfigOptions:traceConfig];"]},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"字段"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"类型"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"说明"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"必须"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"samplerate"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"int"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"采样采集率"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认100)"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"networkTraceType"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"NS_ENUM"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置网络请求信息采集时 使用链路追踪类型，如果接入 OpenTelemetry 选择对应链路类型时，请注意查阅支持类型及 agent 相关配置"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认DDtrace）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableLinkRumData"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"是否将 Trace 数据与 rum 关联"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"enableAutoTrace"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"BOOL"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置是否开启自动 http trace，目前只支持 NSURLSession"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"否（默认NO）"}]}]]],"header":"row"},{"anchor":"链路追踪类型","level":4,"type":"heading","text":"链路追踪类型"},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * @enum"," * 网络链路追踪使用类型"," *"," * @constant"," *  FTNetworkTraceTypeDDtrace       - datadog trace"," *  FTNetworkTraceTypeZipkinMultiHeader   - zipkin multi header"," *  FTNetworkTraceTypeZipkinSingleHeader  - zipkin single header"," *  FTNetworkTraceTypeTraceparent         - w3c traceparent"," *  FTNetworkTraceTypeSkywalking    - skywalking 8.0+"," *  FTNetworkTraceTypeJaeger        - jaeger"," *\/","","typedef NS_ENUM(NSInteger, FTNetworkTraceType) {","    FTNetworkTraceTypeDDtrace,","    FTNetworkTraceTypeZipkinMultiHeader,","    FTNetworkTraceTypeZipkinSingleHeader,","    FTNetworkTraceTypeTraceparent,","    FTNetworkTraceTypeSkywalking,","    FTNetworkTraceTypeJaeger,","};"]},{"anchor":"RUM-用户数据追踪","level":2,"type":"heading","text":"RUM 用户数据追踪"},{"type":"paragraph","inlineContent":[{"type":"text","text":"可以 "},{"type":"codeVoice","code":"FTRUMConfig"},{"type":"text","text":" 配置开启自动模式，或手动添加。Rum 相关数据，通过 "},{"type":"codeVoice","code":"FTExternalDataManager"},{"type":"text","text":" 单例，进行传入，相关 API 如下："}]},{"anchor":"View","level":3,"type":"heading","text":"View"},{"type":"codeListing","syntax":"objectivec","code":["\/\/进入页面时调用  duration 以纳秒为单位 示例中为 1s","[[FTExternalDataManager sharedManager] onCreateView:@\"TestVC\" loadTime:@1000000000];","","[[FTExternalDataManager sharedManager] startViewWithName:@\"TestVC\"];","","[[FTExternalDataManager sharedManager] stopView];"]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * 创建页面 需要在 -startView 与 -stopView 方法前使用 "," * @param viewName     页面名称"," * @param loadTime     页面加载时间"," *\/","-(void)onCreateView:(NSString *)viewName loadTime:(NSNumber *)loadTime;","\/**"," * 进入页面 viewId 内部管理"," * @param viewName        页面名称"," *\/","-(void)startViewWithName:(NSString *)viewName;","\/**"," * 离开页面"," *\/","-(void)stopView;"]},{"anchor":"Action","level":3,"type":"heading","text":"Action"},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * 添加 Click Action 事件"," * @param actionName 事件名称"," *\/","- (void)addClickActionWithName:(NSString *)actionName;"]},{"anchor":"Error","level":3,"type":"heading","text":"Error"},{"type":"codeListing","syntax":"objectivec","code":["[[FTExternalDataManager sharedManager] addErrorWithType:@\"type\" situation:RUN message:@\"message\" stack:@\"stack\"];"]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * 添加 Error 事件"," * @param type       error 类型"," * @param situation  APP状态"," * @param message    错误信息"," * @param stack      堆栈信息"," *\/","- (void)addErrorWithType:(NSString *)type situation:(AppState)situation message:(NSString *)message stack:(NSString *)stack;"]},{"anchor":"LongTask","level":3,"type":"heading","text":"LongTask"},{"type":"codeListing","syntax":"objectivec","code":["[[FTExternalDataManager sharedManager] addLongTaskWithStack:@\"堆栈信息 string\" duration:@1000000000];"]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * 添加 卡顿 事件"," * @param stack      卡顿堆栈"," * @param duration   卡顿时长 (纳秒级)"," *\/","- (void)addLongTaskWithStack:(NSString *)stack duration:(NSNumber *)duration;"]},{"anchor":"Resource","level":3,"type":"heading","text":"Resource"},{"type":"codeListing","syntax":"objectivec","code":["\/\/第一步：请求开始前","[[FTExternalDataManager sharedManager] startResourceWithKey:key];","","\/\/第二部：请求完成","[[FTExternalDataManager sharedManager] stopResourceWithKey:key];","","\/\/第三步：拼接 Resource 数据","\/\/FTResourceContentModel 数据"," FTResourceContentModel *content = [[FTResourceContentModel alloc]init];","        content.httpMethod = request.HTTPMethod;","        content.requestHeader = request.allHTTPHeaderFields;","        content.responseHeader = httpResponse.allHeaderFields;","        content.httpStatusCode = httpResponse.statusCode;","        content.responseBody = responseBody;","        \/\/ios native","        content.error = error;","\/\/如果能获取到各阶段的时间数据 FTResourceMetricsModel","   \/\/ios 原生 获取到 NSURLSessionTaskMetrics 数据 直接使用 FTResourceMetricsModel的初始化方法","    FTResourceMetricsModel *metricsModel = [[FTResourceMetricsModel alloc]initWithTaskMetrics:metrics];","  ","  \/\/其他平台 所有时间数据以纳秒为单位","   FTResourceMetricsModel *metricsModel = [[FTResourceMetricsModel alloc]init];","   [metricsModel setDnsStart:dstart end:dend];","   [metricsModel setTcpStart:tstart end:tend];","   [metricsModel setSslStart:sstart end:send];","   [metricsModel setTtfbStart:ttstart end:ttend];","   [metricsModel setTransStart:trstart end:trend];","   [metricsModel setFirstByteStart:fstart end:fend];","   [metricsModel setDurationStart:dstart end:dend];","","","\/\/ 第四部：add resource 如果没有时间数据 metrics 传 nil"," [[FTExternalDataManager sharedManager] addResourceWithKey:key metrics:metricsModel content:content];"]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * @param key       请求标识"," *\/","- (void)startResourceWithKey:(NSString *)key;","\/**"," * @param key       请求标识"," *\/","- (void)stopResourceWithKey:(NSString *)key;","\/**"," * @param key       请求标识"," * @param metrics   请求相关性能属性"," * @param content   请求相关数据"," *\/","- (void)addResourceWithKey:(NSString *)key metrics:(nullable FTResourceMetricsModel *)metrics content:(FTResourceContentModel *)content;"]},{"anchor":"Logger-日志打印-user-logger","level":2,"type":"heading","text":"Logger 日志打印 {#user-logger}"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"上传机制"}]},{"type":"text","text":" : 将数据存储到数据库中，等待时机进行上传。数据库存储量限制在 5000 条，如果网络异常等原因导致数据堆积，存储 5000 条后，会丢弃新传入的数据。"}]},{"type":"codeListing","syntax":"objectivec","code":["[[FTMobileAgent sharedInstance] logging:@\"TestLoggingBackground\" status:FTStatusInfo];"]},{"anchor":"日志等级","level":3,"type":"heading","text":"日志等级"},{"type":"codeListing","syntax":"objectivec","code":["typedef NS_ENUM(NSInteger, FTStatus) {","    FTStatusInfo         = 0,","    FTStatusWarning,","    FTStatusError,","    FTStatusCritical,","    FTStatusOk,","};","\/**"," * 日志上报"," * @param content  日志内容，可为json字符串"," * @param status   事件等级和状态，info：提示，warning：警告，error：错误，critical：严重，ok：恢复，默认：info",""," *\/","-(void)logging:(NSString *)content status:(FTStatus)status;"]},{"anchor":"Trace-网络链接追踪","level":2,"type":"heading","text":"Trace 网络链接追踪"},{"type":"paragraph","inlineContent":[{"type":"text","text":"可以 "},{"type":"codeVoice","code":"FTTraceConfig"},{"type":"text","text":" 配置开启自动模式，或手动添加。Trace 相关数据，通过 "},{"type":"codeVoice","code":"FTTraceManager"},{"type":"text","text":" 单例，进行传入，相关 API 如下："}]},{"type":"codeListing","syntax":"objectivec","code":[" NSString *key = [[NSUUID UUID]UUIDString];","    NSURL *url = [NSURL URLWithString:@\"http:\/\/www.baidu.com\"];","\/\/需要的手动操作： 请求前获取 traceHeader 添加到请求头","    NSDictionary *traceHeader = [[FTTraceManager sharedInstance] getTraceHeaderWithKey:key url:url];","    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];","    if (traceHeader && traceHeader.allKeys.count>0) {","        [traceHeader enumerateKeysAndObjectsUsingBlock:^(id field, id value, BOOL * __unused stop) {","            [request setValue:value forHTTPHeaderField:field];","        }];","    }","    NSURLSession *session=[NSURLSession sessionWithConfiguration:[NSURLSessionConfiguration defaultSessionConfiguration] delegate:self delegateQueue:[NSOperationQueue mainQueue]];","    ","    NSURLSessionTask *task = [session dataTaskWithRequest:request completionHandler:^(NSData * _Nullable data, NSURLResponse * _Nullable response, NSError * _Nullable error) {","       \/\/您的代码","    }];","    ","    [task resume];"]},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * 获取 trace 请求头"," * @param key 请求标识"," *\/","- (NSDictionary *)getTraceHeaderWithKey:(NSString *)key url:(NSURL *)url;",""]},{"anchor":"用户的绑定与注销","level":2,"type":"heading","text":"用户的绑定与注销"},{"type":"codeListing","syntax":"objectivec","code":["\/**"," * 登录后 绑定用户信息"," * @param Id        用户Id"," * @param userName  用户名称"," * @param extra     用户的额外信息","*\/","[[FTMobileAgent sharedInstance] bindUserWithUserID:USERID];","\/\/or","[[FTMobileAgent sharedInstance] bindUserWithUserID:USERID userName:USERNAME userEmail:USEREMAIL];","\/\/or","[[FTMobileAgent sharedInstance] bindUserWithUserID:USERID userName:USERNAME userEmail:USEREMAIL extra:@{EXTRA_KEY:EXTRA_VALUE}];","","\/\/登出后 注销当前用户","[[FTMobileAgent sharedInstance] logout];"]},{"anchor":"添加自定义标签-user-global-context","level":2,"type":"heading","text":"添加自定义标签 {#user-global-context}"},{"anchor":"静态使用","level":3,"type":"heading","text":"静态使用"},{"type":"paragraph","inlineContent":[{"type":"text","text":"可采用创建多 Configurations ，使用预编译指令进行设置值"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"创建多 Configurations ："}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"image_9.png"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"设置预设属性来区分不同 Configurations:"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"image_10.png"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"使用预编译指令："}]}]}]},{"type":"codeListing","syntax":"objectivec","code":["\/\/Target -> Build Settings -> GCC_PREPROCESSOR_DEFINITIONS 进行配置预设定义","#if PRE","#define Track_id       @\"0000000001\"","#define STATIC_TAG     @\"preprod\"","#elif  DEVELOP","#define Track_id       @\"0000000002\"","#define STATIC_TAG     @\"common\"","#else","#define Track_id       @\"0000000003\"","#define STATIC_TAG     @\"prod\"","#endif","   ","FTRumConfig *rumConfig = [[FTRumConfig alloc]init]; ","rumConfig.globalContext = @{@\"track_id\":Track_id,@\"static_tag\":STATIC_TAG};","... \/\/其他设置操作","[[FTMobileAgent sharedInstance] startRumWithConfigOptions:rumConfig];"]},{"anchor":"动态使用","level":3,"type":"heading","text":"动态使用"},{"type":"paragraph","inlineContent":[{"type":"text","text":"因 RUM 启动后设置的 globalContext 不会生效，用户可自行本地保存，在下次应用启动时进行设置生效。"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"通过存文件本地保存，例如"},{"type":"codeVoice","code":"NSUserDefaults"},{"type":"text","text":"，配置使用 "},{"type":"codeVoice","code":"SDK"},{"type":"text","text":"，在配置处添加获取标签数据的代码。"}]}]}]},{"type":"codeListing","syntax":"objectivec","code":["NSString *dynamicTag = [[NSUserDefaults standardUserDefaults] valueForKey:@\"DYNAMIC_TAG\"]?:@\"NO_VALUE\";","","FTRumConfig *rumConfig = [[FTRumConfig alloc]init];","rumConfig.globalContext = @{@\"dynamic_tag\":dynamicTag};","... \/\/其他设置操作","[[FTMobileAgent sharedInstance] startRumWithConfigOptions:rumConfig];"]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"在任意处添加改变文件数据的方法。"}]}]}]},{"type":"codeListing","syntax":"objectivec","code":[" [[NSUserDefaults standardUserDefaults] setValue:@\"dynamic_tags\" forKey:@\"DYNAMIC_TAG\"];"]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"最后重启应用生效。"}]}]}]},{"anchor":"注意","level":3,"type":"heading","text":"注意"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"特殊 key : track_id (在 RUM 中配置，用于追踪功能)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"当用户通过 globalContext 添加自定义标签与 SDK 自有标签相同时，SDK 的标签会覆盖用户设置的，建议标签命名添加项目缩写的前缀，例如 "},{"type":"codeVoice","code":"df_tag_name"},{"type":"text","text":"。"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"在调用 -startRumWithConfigOptions 方法启动 RUM 前设置 globalContext 才能生效。"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"FTMobileConfig"},{"type":"text","text":" 中配置的自定义标签将添加在所有类型的数据中。"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"详细细节请见 "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/DataFlux-cn\/datakit-ios\/tree\/develop\/demo"},{"type":"text","text":"。"}]},{"anchor":"崩溃日志符号化","level":2,"type":"heading","text":"崩溃日志符号化"},{"anchor":"上传符号表","level":3,"type":"heading","text":"上传符号表"},{"anchor":"方法一脚本集成到-Xcode-工程的-Target","level":4,"type":"heading","text":"方法一：脚本集成到 Xcode 工程的 Target"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"XCode 添加自定义 Run Script Phase："},{"type":"codeVoice","code":" Build Phases -> + -> New Run Script Phase"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"将脚本复制到 Xcode 项目的构建阶段运行脚本中，脚本中需要设置参数如：＜app_id＞、＜dea_address＞、＜env＞、＜version＞(脚本默认配置的版本格式为 "},{"type":"codeVoice","code":"CFBundleShortVersionString"},{"type":"text","text":")。"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/blob\/develop\/demo\/FTdSYMUploader.sh"}]}]}]},{"type":"codeListing","syntax":"sh","code":["#脚本中需要配置的参数","#＜app_id＞","FT_APP_ID=\"YOUR_APP_ID\"","#＜dea_address＞","FT_DEA_ADDRESS=\"YOUR_DEA_ADDRESS\"","# ＜env＞ 环境字段。属性值：prod\/gray\/pre\/common\/local。需要与 SDK 设置一致","FT_ENV=\"common\"","#","#＜version＞ 脚本默认配置的版本格式为CFBundleShortVersionString,如果你修改默认的版本格式, 请设置此变量。注意：需要确保在此填写的与SDK设置的一致。","# FT_VERSION=\"\""]},{"anchor":"多环境便捷的配置参数","level":5,"type":"heading","text":"多环境便捷的配置参数"},{"type":"paragraph","inlineContent":[{"type":"text","text":"示例：使用预设宏和 .xcconfig 配置文件"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"添加预设宏："},{"type":"codeVoice","code":"Target —> Build Settings -> + -> Add User-Defined Setting"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration1.png"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration2.png"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"使用多 Xcconfig 来实现多环境，新建 Xcconfig"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration3.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":".xcconfig 文件中配置预设宏："}]},{"type":"codeListing","syntax":"sh","code":["\/\/如果有使用 cocoapods 将 pods 的.xcconfig路径 添加到你的 .xcconfig文件中 如果路径不清楚可以终端进入项目文件夹，pod install ,终端会有提示路径，将该路径复制后引用就可以。","","#include \"Pods\/Target Support Files\/Pods-testDemo\/Pods-testDemo.debug.xcconfig\"","","SDK_APP_ID = app_id_common","SDK_ENV = common","SDK_DEA_ADDRESS = http:\\$()\\xxxxxxxx:9531 "]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"配置自定义编译环境"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration4.png"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration5.png"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"使用"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"脚本中"}]}]},{"type":"codeListing","syntax":"sh","code":["#脚本中需要配置的参数","#＜app_id＞","FT_APP_ID=SDK_APP_ID","#＜dea_address＞","FT_DEA_ADDRESS=SDK_DEA_ADDRESS","# ＜env＞ 环境字段。属性值：prod\/gray\/pre\/common\/local。需要与 SDK 设置一致","FT_ENV=SDK_ENV"]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"项目某一文件中"}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"方法一：对指定文件进行配置：-D’SDK_APP_ID=@”$(SDK_APP_ID)”’"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration6.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"在指定文件中可以使用"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration7.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"方法二：映射到  "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":" 文件中"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration8.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"在文件中可以使用"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"multi-environment-configuration9.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"详细细节请见 "},{"overridingTitleInlineContent":[{"type":"text","text":"SDK Demo"}],"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/DataFlux-cn\/datakit-ios\/tree\/develop\/demo","overridingTitle":"SDK Demo"},{"type":"text","text":"。"}]},{"anchor":"方法二终端运行脚本","level":4,"type":"heading","text":"方法二：终端运行脚本"},{"type":"paragraph","inlineContent":[{"type":"text","text":"找到 .dSYM 文件放在一个文件夹内，命令行下输入应用基本信息, .dSYM 文件的父目录路径, 输出文件目录即可"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"sh FTdSYMUpload.sh <dea_address> <app_id> <version> <env> <dSYMBOL_src_dir> <dSYMBOL_dest_dir>"}]},{"anchor":"方法三手动上传","level":4,"type":"heading","text":"方法三：手动上传"},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"..\/..\/datakit\/rum.md#sourcemap"}]},{"anchor":"常见问题-FAQ","level":2,"type":"heading","text":"常见问题 {#FAQ}"},{"anchor":"关于崩溃日志分析","level":3,"type":"heading","text":"关于崩溃日志分析"},{"type":"paragraph","inlineContent":[{"type":"text","text":"在开发时的 "},{"type":"strong","inlineContent":[{"type":"text","text":"Debug"}]},{"type":"text","text":" 和 "},{"type":"strong","inlineContent":[{"type":"text","text":"Release"}]},{"type":"text","text":" 模式下， "},{"type":"strong","inlineContent":[{"type":"text","text":"Crash"}]},{"type":"text","text":" 时捕获的线程回溯是被符号化的。"},{"type":"text","text":" "},{"type":"text","text":"而发布包没带符号表，异常线程的关键回溯，会显示镜像的名字，不会转化为有效的代码符号，获取到的 "},{"type":"strong","inlineContent":[{"type":"text","text":"crash log"}]},{"type":"text","text":" 中的相关信息都是 16 进制的内存地址，并不能定位崩溃的代码，所以需要将 16 进制的内存地址解析为对应的类及方法。"}]},{"anchor":"XCode-编译后没有生成-dSYM-文件","level":4,"type":"heading","text":"XCode 编译后没有生成 dSYM 文件？"},{"type":"paragraph","inlineContent":[{"type":"text","text":"XCode Release 编译默认会生成 dSYM 文件，而 Debug 编译默认不会生成，对应的 Xcode 配置如下："}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":" Build Settings -> Code Generation -> Generate Debug Symbols -> Yes"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"dsym_config1.png"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":" Build Settings -> Build Option -> Debug Information Format -> DWARF with dSYM File"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"dsym_config2.png"}]},{"anchor":"开启了-bitCode-怎么上传符号表","level":4,"type":"heading","text":"开启了 bitCode 怎么上传符号表？"},{"type":"paragraph","inlineContent":[{"type":"text","text":"当你上传你的 bitcode App 到 App Store，在提交对话框里勾选声明符号文件（dSYM文件）的生成："}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"在配置符号表文件之前，需要从App Store中把该版本对应的dSYM文件下载回本地，然后用脚本根据输入参数处理上传符号表文件。"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"不需要将脚本集成到 Xcode 工程的 Target 了，也不要用本地生成的 dSYM 文件来生成符号表文件，因为本地编译生成的 dSYM 文件的符号表信息都被隐藏了。如果用本地编译生成的 dSYM 文件上传，还原出来的结果将是类似于“__hiden#XXX”这样的符号。"}]}]}]},{"anchor":"如何找回已发布到-App-Store-的-App-对应的-dSYM-文件","level":4,"type":"heading","text":"如何找回已发布到 App Store 的 App 对应的 dSYM 文件？"},{"type":"table","rows":[[[{"type":"paragraph","inlineContent":[{"type":"text","text":"应用上传到App  Store Connect的Distribution options"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"dSym文件"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Don’t include bitcode"},{"type":"text","text":"Upload symbols"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"通过 Xcode 找回"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Include bitcode"},{"type":"text","text":"Upload symbols"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"通过 iTunes Connect 找回"},{"type":"text","text":"通过 Xcode 找回， 需要使用 "},{"type":"codeVoice","code":".bcsymbolmap"},{"type":"text","text":" 去混淆处理。"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Include bitcode"},{"type":"text","text":"Don’t upload symbols"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"通过 Xcode 找回， 需要使用 "},{"type":"codeVoice","code":".bcsymbolmap"},{"type":"text","text":" 去混淆处理。"}]}]],[[{"type":"paragraph","inlineContent":[{"type":"text","text":"Don’t include bitcode"},{"type":"text","text":"Don’t upload symbols"}]}],[{"type":"paragraph","inlineContent":[{"type":"text","text":"通过 Xcode 找回"}]}]]],"header":"row"},{"anchor":"通过-Xcode-找回","level":5,"type":"heading","text":"通过 Xcode 找回"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Xcode -> Window -> Organizer "}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"选择 "},{"type":"codeVoice","code":"Archives"},{"type":"text","text":"  标签"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"xcode_find_dsym2.png"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"找到发布的归档包，右键点击对应归档包，选择Show in Finder操作"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"xcode_find_dsym3.png"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"右键选择定位到的归档文件，选择显示包内容操作"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"xcode_find_dsym4.png"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"选择dSYMs目录，目录内即为下载到的 dSYM 文件"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"xcode_find_dsym5.png"}]}]}]},{"anchor":"通过-iTunes-Connect-找回","level":5,"type":"heading","text":"通过 iTunes Connect 找回"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"登录"},{"type":"reference","isActive":true,"identifier":"https:\/\/appstoreconnect.apple.com"},{"type":"text","text":"；"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"进入”我的App（My Apps）”"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"在 “App Store” 或 “TestFlight” 中选择某一个版本”，点击 “构建版本元数据（Build Metadata）” 在此页面，点击按钮 “下载dSYM（Download dSYM）” 下载 dSYM 文件"}]}]}]},{"anchor":"bcsymbolmap-去混淆处理","level":5,"type":"heading","text":".bcsymbolmap 去混淆处理"},{"type":"paragraph","inlineContent":[{"type":"text","text":"在通过 Xcode 找到 dSYM 文件时，可以看到 BCSymbolMaps 目录"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"BCSymbolMaps.png"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"打开终端并使用以下命令进行去混淆处理"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"xcrun dsymutil -symbol-map <BCSymbolMaps_path> <.dSYM_path>"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/app-access"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/app-access"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/app-access","interfaceLanguage":"swift"},"kind":"article","metadata":{"roleHeading":"Article","title":"iOS 应用接入","role":"article","modules":[{"name":"FTMobileAgent"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/tutorials\/Meet-FTMobileSDK"],"generated":true}],"references":{"../../datakit/datakit-install.md":{"title":"DataKit 安装文档","titleInlineContent":[{"type":"text","text":"DataKit 安装文档"}],"type":"link","identifier":"..\/..\/datakit\/datakit-install.md","url":"..\/..\/datakit\/datakit-install.md"},"https://img.shields.io/cocoapods/p/FTMobileAgent#crop=0&crop=0&crop=1&crop=1&id=xs5E2&originHeight=20&originWidth=82&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=":{"alt":null,"type":"image","identifier":"https:\/\/img.shields.io\/cocoapods\/p\/FTMobileAgent#crop=0&crop=0&crop=1&crop=1&id=xs5E2&originHeight=20&originWidth=82&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=","variants":[{"url":"https:\/\/img.shields.io\/cocoapods\/p\/FTMobileAgent#crop=0&crop=0&crop=1&crop=1&id=xs5E2&originHeight=20&originWidth=82&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=","traits":["1x","light"]}]},"xcode_find_dsym3.png":{"alt":null,"type":"image","identifier":"xcode_find_dsym3.png","variants":[{"url":"\/images\/xcode_find_dsym3.png","traits":["1x","light"]}]},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/tutorials/Meet-FTMobileSDK":{"role":"overview","title":"应用监测 配置教程","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/tutorials\/Meet-FTMobileSDK","kind":"overview","type":"topic","url":"\/tutorials\/meet-ftmobilesdk"},"13.rum_access_3.png":{"alt":null,"type":"image","identifier":"13.rum_access_3.png","variants":[{"url":"\/images\/13.rum_access_3.png","traits":["1x","light"]}]},"xcode_find_dsym2.png":{"alt":null,"type":"image","identifier":"xcode_find_dsym2.png","variants":[{"url":"\/images\/xcode_find_dsym2.png","traits":["1x","light"]}]},"multi-environment-configuration4.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration4.png","variants":[{"url":"\/images\/multi-environment-configuration4.png","traits":["1x","light"]}]},"BCSymbolMaps.png":{"alt":null,"type":"image","identifier":"BCSymbolMaps.png","variants":[{"url":"\/images\/BCSymbolMaps.png","traits":["1x","light"]}]},"xcode_find_dsym4.png":{"alt":null,"type":"image","identifier":"xcode_find_dsym4.png","variants":[{"url":"\/images\/xcode_find_dsym4.png","traits":["1x","light"]}]},"multi-environment-configuration8.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration8.png","variants":[{"url":"\/images\/multi-environment-configuration8.png","traits":["1x","light"]}]},"https://img.shields.io/cocoapods/l/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=SxRum&originHeight=20&originWidth=98&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=":{"alt":null,"type":"image","identifier":"https:\/\/img.shields.io\/cocoapods\/l\/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=SxRum&originHeight=20&originWidth=98&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=","variants":[{"url":"https:\/\/img.shields.io\/cocoapods\/l\/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=SxRum&originHeight=20&originWidth=98&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=","traits":["1x","light"]}]},"image_10.png":{"alt":null,"type":"image","identifier":"image_10.png","variants":[{"url":"\/images\/image_10.png","traits":["1x","light"]}]},"xcode_find_dsym5.png":{"alt":null,"type":"image","identifier":"xcode_find_dsym5.png","variants":[{"url":"\/images\/xcode_find_dsym5.png","traits":["1x","light"]}]},"multi-environment-configuration6.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration6.png","variants":[{"url":"\/images\/multi-environment-configuration6.png","traits":["1x","light"]}]},"dsym_config2.png":{"alt":null,"type":"image","identifier":"dsym_config2.png","variants":[{"url":"\/images\/dsym_config2.png","traits":["1x","light"]}]},"image_9.png":{"alt":null,"type":"image","identifier":"image_9.png","variants":[{"url":"\/images\/image_9.png","traits":["1x","light"]}]},"https://img.shields.io/cocoapods/v/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=Uyl38&originHeight=20&originWidth=122&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=":{"alt":null,"type":"image","identifier":"https:\/\/img.shields.io\/cocoapods\/v\/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=Uyl38&originHeight=20&originWidth=122&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=","variants":[{"url":"https:\/\/img.shields.io\/cocoapods\/v\/FTMobileSDK#crop=0&crop=0&crop=1&crop=1&id=Uyl38&originHeight=20&originWidth=122&originalType=binary&ratio=1&rotation=0&showTitle=false&status=done&style=none&title=","traits":["1x","light"]}]},"multi-environment-configuration1.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration1.png","variants":[{"url":"\/images\/multi-environment-configuration1.png","traits":["1x","light"]}]},"multi-environment-configuration9.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration9.png","variants":[{"url":"\/images\/multi-environment-configuration9.png","traits":["1x","light"]}]},"https://appstoreconnect.apple.com":{"title":"App Store Connect","titleInlineContent":[{"type":"text","text":"App Store Connect"}],"type":"link","identifier":"https:\/\/appstoreconnect.apple.com","url":"https:\/\/appstoreconnect.apple.com"},"multi-environment-configuration5.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration5.png","variants":[{"url":"\/images\/multi-environment-configuration5.png","traits":["1x","light"]}]},"multi-environment-configuration3.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration3.png","variants":[{"url":"\/images\/multi-environment-configuration3.png","traits":["1x","light"]}]},"dsym_config1.png":{"alt":null,"type":"image","identifier":"dsym_config1.png","variants":[{"url":"\/images\/dsym_config1.png","traits":["1x","light"]}]},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"https://github.com/GuanceCloud/datakit-ios/blob/develop/demo/FTdSYMUploader.sh":{"title":"脚本","titleInlineContent":[{"type":"text","text":"脚本"}],"type":"link","identifier":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/blob\/develop\/demo\/FTdSYMUploader.sh","url":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/blob\/develop\/demo\/FTdSYMUploader.sh"},"https://github.com/GuanceCloud/datakit-ios/tree/develop/demo":{"title":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/demo","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/demo"}],"type":"link","identifier":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/tree\/develop\/demo","url":"https:\/\/github.com\/GuanceCloud\/datakit-ios\/tree\/develop\/demo"},"multi-environment-configuration2.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration2.png","variants":[{"url":"\/images\/multi-environment-configuration2.png","traits":["1x","light"]}]},"#user-logger":{"title":"自定义上报日志","titleInlineContent":[{"type":"text","text":"自定义上报日志"}],"type":"link","identifier":"#user-logger","url":"#user-logger"},"multi-environment-configuration7.png":{"alt":null,"type":"image","identifier":"multi-environment-configuration7.png","variants":[{"url":"\/images\/multi-environment-configuration7.png","traits":["1x","light"]}]},"#user-global-context":{"title":"添加自定义标签","titleInlineContent":[{"type":"text","text":"添加自定义标签"}],"type":"link","identifier":"#user-global-context","url":"#user-global-context"},"../../datakit/rum.md#sourcemap":{"title":"Sourcemap 上传","titleInlineContent":[{"type":"text","text":"Sourcemap 上传"}],"type":"link","identifier":"..\/..\/datakit\/rum.md#sourcemap","url":"..\/..\/datakit\/rum.md#sourcemap"},"https://github.com/GuanceCloud/datakit-ios":{"title":"https:\/\/github.com\/GuanceCloud\/datakit-ios","titleInlineContent":[{"type":"text","text":"https:\/\/github.com\/GuanceCloud\/datakit-ios"}],"type":"link","identifier":"https:\/\/github.com\/GuanceCloud\/datakit-ios","url":"https:\/\/github.com\/GuanceCloud\/datakit-ios"},"https://github.com/DataFlux-cn/datakit-ios/tree/develop/demo":{"title":"SDK Demo","titleInlineContent":[{"type":"text","text":"SDK Demo"}],"type":"link","identifier":"https:\/\/github.com\/DataFlux-cn\/datakit-ios\/tree\/develop\/demo","url":"https:\/\/github.com\/DataFlux-cn\/datakit-ios\/tree\/develop\/demo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/tutorials\/Meet-FTMobileSDK"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}