{"seeAlsoSections":[{"title":"Enumerations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"title":"FTDeviceMetricsMonitorType","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@E@FTDeviceMetricsMonitorType","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}]},"abstract":[{"type":"text","text":"设备信息监控项"}],"sections":[],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s25ExpressibleByArrayLiteralP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s9OptionSetP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/all","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/cpu","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/fps","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/memory"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/Equatable-Implementations","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/OptionSet-Implementations","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/SetAlgebra-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType":{"role":"symbol","title":"FTNetworkTraceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"}],"abstract":[{"type":"text","text":"网络链路追踪使用类型"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceType"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/init(rawvalue:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/memory":{"role":"symbol","title":"memory","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"平均内存、最高内存"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/memory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorMemory"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/memory"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/optionset-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/setalgebra-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTEnv":{"role":"symbol","title":"FTEnv","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTEnv"}],"abstract":[{"type":"text","text":"环境字段。属性值：prod\/gray\/pre\/common\/local。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTEnv"}],"url":"\/documentation\/ftmobileagent\/ftenv"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/all":{"role":"symbol","title":"all","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"开启所有监控项:内存、CPU、FPS"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorAll"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/all"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency":{"role":"symbol","title":"FTMonitorFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMonitorFrequency"}],"abstract":[{"type":"text","text":"监控项采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s25ExpressibleByArrayLiteralP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus":{"role":"symbol","title":"FTLogStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogStatus"}],"abstract":[{"type":"text","text":"事件等级和状态，默认：FTStatusInfo"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLogStatus"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s10SetAlgebraP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s9OptionSetP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/fps":{"role":"symbol","title":"fps","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"fps 最低帧率、平均帧率"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/fps","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorFps"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/fps"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTErrorMonitorType":{"role":"symbol","title":"FTErrorMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTErrorMonitorType"}],"abstract":[{"type":"text","text":"ERROR 中的设备信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTErrorMonitorType"}],"url":"\/documentation\/ftmobileagent\/fterrormonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/equatable-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType":{"role":"symbol","title":"FTDeviceMetricsMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"设备信息监控项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType/cpu":{"role":"symbol","title":"cpu","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"CPU 跳动最大、平均数"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/cpu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorCpu"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype\/cpu"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard":{"role":"symbol","title":"FTLogCacheDiscard","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogCacheDiscard"}],"abstract":[{"type":"text","text":"日志废弃策略"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLogCacheDiscard"}],"url":"\/documentation\/ftmobileagent\/ftlogcachediscard"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FTDeviceMetricsMonitorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/all","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/cpu","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/fps","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType\/memory"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Enumerations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTDeviceMetricsMonitorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/title","value":"FTNetworkTraceType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1memory\/title","value":"FTDeviceMetricsMonitorMemory"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1memory\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorMemory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTEnv\/title","value":"FTEnv"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTEnv\/fragments","value":[{"kind":"identifier","text":"FTEnv"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1all\/title","value":"FTDeviceMetricsMonitorAll"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1all\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/title","value":"FTMonitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus\/title","value":"FTLogStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus\/fragments","value":[{"kind":"identifier","text":"FTLogStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1fps\/title","value":"FTDeviceMetricsMonitorFps"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1fps\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorFps"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/title","value":"FTErrorMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/fragments","value":[{"kind":"identifier","text":"FTErrorMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/title","value":"FTDeviceMetricsMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1cpu\/title","value":"FTDeviceMetricsMonitorCpu"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType~1cpu\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorCpu"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/title","value":"FTLogCacheDiscard"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/fragments","value":[{"kind":"identifier","text":"FTLogCacheDiscard"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}