{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogCacheDiscard"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"termList","items":[{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"默认，当日志数据大于最大值时 废弃新传入的数据"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTDiscard"}]}},{"definition":{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"当日志数据大于最大值时,废弃旧数据"}]}]},"term":{"inlineContent":[{"type":"text","text":"FTDiscardOldest"}]}}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftlogcachediscard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftlogcachediscard"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"日志废弃策略"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogCacheDiscard"}],"title":"FTLogCacheDiscard","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@FTLogCacheDiscard","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTLogCacheDiscard"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/discard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/discardOldest"]},{"title":"Initializers","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/Equatable-Implementations","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard/discard":{"role":"symbol","title":"FTLogCacheDiscard.discard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"discard"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/discard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDiscard"}],"url":"\/documentation\/ftmobileagent\/ftlogcachediscard\/discard"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent\/ftlogcachediscard\/init(rawvalue:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftlogcachediscard\/equatable-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard":{"role":"symbol","title":"FTLogCacheDiscard","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogCacheDiscard"}],"abstract":[{"type":"text","text":"日志废弃策略"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLogCacheDiscard"}],"url":"\/documentation\/ftmobileagent\/ftlogcachediscard"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard/discardOldest":{"role":"symbol","title":"FTLogCacheDiscard.discardOldest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"discardOldest"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/discardOldest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDiscardOldest"}],"url":"\/documentation\/ftmobileagent\/ftlogcachediscard\/discardoldest"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftlogcachediscard\/rawrepresentable-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FTLogCacheDiscard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTLogCacheDiscard"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTLogCacheDiscard"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/discard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard\/discardOldest"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogCacheDiscard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard~1discard\/title","value":"FTDiscard"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard~1discard\/fragments","value":[{"kind":"identifier","text":"FTDiscard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/title","value":"FTLogCacheDiscard"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/fragments","value":[{"kind":"identifier","text":"FTLogCacheDiscard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard~1discardOldest\/title","value":"FTDiscardOldest"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard~1discardOldest\/fragments","value":[{"kind":"identifier","text":"FTDiscardOldest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}