{"seeAlsoSections":[{"title":"Enumerations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogStatus"}],"title":"FTLogStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@FTLogStatus","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTLogStatus"}]},"abstract":[{"type":"text","text":"事件等级和状态，默认：FTStatusInfo"}],"sections":[],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusCritical","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusError","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusInfo","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusOk","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusWarning"]},{"title":"Initializers","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/Equatable-Implementations","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftlogstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftlogstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent\/ftlogstatus\/init(rawvalue:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/statusWarning":{"role":"symbol","title":"FTLogStatus.statusWarning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusWarning"}],"abstract":[{"type":"text","text":"警告"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusWarning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTStatusWarning"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus\/statuswarning"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/statusInfo":{"role":"symbol","title":"FTLogStatus.statusInfo","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusInfo"}],"abstract":[{"type":"text","text":"提示"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTStatusInfo"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus\/statusinfo"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus":{"role":"symbol","title":"FTLogStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogStatus"}],"abstract":[{"type":"text","text":"事件等级和状态，默认：FTStatusInfo"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLogStatus"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s8SendableP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTErrorMonitorType":{"role":"symbol","title":"FTErrorMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTErrorMonitorType"}],"abstract":[{"type":"text","text":"ERROR 中的设备信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTErrorMonitorType"}],"url":"\/documentation\/ftmobileagent\/fterrormonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/statusCritical":{"role":"symbol","title":"FTLogStatus.statusCritical","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusCritical"}],"abstract":[{"type":"text","text":"严重"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusCritical","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTStatusCritical"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus\/statuscritical"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogCacheDiscard":{"role":"symbol","title":"FTLogCacheDiscard","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogCacheDiscard"}],"abstract":[{"type":"text","text":"日志废弃策略"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLogCacheDiscard"}],"url":"\/documentation\/ftmobileagent\/ftlogcachediscard"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/statusOk":{"role":"symbol","title":"FTLogStatus.statusOk","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusOk"}],"abstract":[{"type":"text","text":"恢复"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusOk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTStatusOk"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus\/statusok"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftlogstatus\/equatable-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTEnv":{"role":"symbol","title":"FTEnv","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTEnv"}],"abstract":[{"type":"text","text":"环境字段。属性值：prod\/gray\/pre\/common\/local。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTEnv"}],"url":"\/documentation\/ftmobileagent\/ftenv"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/ftmobileagent\/ftlogstatus\/rawrepresentable-implementations"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLogStatus/statusError":{"role":"symbol","title":"FTLogStatus.statusError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusError"}],"abstract":[{"type":"text","text":"错误"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTStatusError"}],"url":"\/documentation\/ftmobileagent\/ftlogstatus\/statuserror"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency":{"role":"symbol","title":"FTMonitorFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMonitorFrequency"}],"abstract":[{"type":"text","text":"监控项采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SY"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTDeviceMetricsMonitorType":{"role":"symbol","title":"FTDeviceMetricsMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"设备信息监控项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}],"url":"\/documentation\/ftmobileagent\/ftdevicemetricsmonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTNetworkTraceType":{"role":"symbol","title":"FTNetworkTraceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTNetworkTraceType"}],"abstract":[{"type":"text","text":"网络链路追踪使用类型"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTNetworkTraceType"}],"url":"\/documentation\/ftmobileagent\/ftnetworktracetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"FTLogStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTLogStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTLogStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusCritical","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusError","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusInfo","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusOk","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogStatus\/statusWarning"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Enumerations","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTEnv","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTDeviceMetricsMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLogCacheDiscard","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTNetworkTraceType"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLogStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusWarning\/title","value":"FTStatusWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusWarning\/fragments","value":[{"kind":"identifier","text":"FTStatusWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusInfo\/title","value":"FTStatusInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusInfo\/fragments","value":[{"kind":"identifier","text":"FTStatusInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus\/title","value":"FTLogStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus\/fragments","value":[{"kind":"identifier","text":"FTLogStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/title","value":"FTErrorMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/fragments","value":[{"kind":"identifier","text":"FTErrorMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusCritical\/title","value":"FTStatusCritical"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusCritical\/fragments","value":[{"kind":"identifier","text":"FTStatusCritical"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/title","value":"FTLogCacheDiscard"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogCacheDiscard\/fragments","value":[{"kind":"identifier","text":"FTLogCacheDiscard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusOk\/title","value":"FTStatusOk"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusOk\/fragments","value":[{"kind":"identifier","text":"FTStatusOk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTEnv\/title","value":"FTEnv"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTEnv\/fragments","value":[{"kind":"identifier","text":"FTEnv"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusError\/title","value":"FTStatusError"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLogStatus~1statusError\/fragments","value":[{"kind":"identifier","text":"FTStatusError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/title","value":"FTMonitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/title","value":"FTDeviceMetricsMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTDeviceMetricsMonitorType\/fragments","value":[{"kind":"identifier","text":"FTDeviceMetricsMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/title","value":"FTNetworkTraceType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTNetworkTraceType\/fragments","value":[{"kind":"identifier","text":"FTNetworkTraceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}