{"seeAlsoSections":[{"title":"Classes","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"title":"FTMobileAgent","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)FTMobileAgent","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTMobileAgent"}]},"abstract":[{"type":"text","text":"FTMobileSDK"}],"sections":[],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s7CVarArgP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s28CustomDebugStringConvertibleP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s23CustomStringConvertibleP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:userName:userEmail:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:userName:userEmail:extra:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/isIntakeUrl(_:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logging(_:status:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logging(_:status:property:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logout()","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startLogger(withConfigOptions:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startRum(withConfigOptions:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startTrace(withConfigOptions:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/trackEventFromExtension(withGroupIdentifier:completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/sharedInstance()","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/start(withConfigOptions:)"]}],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftmobileagent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftmobileagent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/logout()":{"role":"symbol","title":"logout()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"注销当前用户"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logout()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logout"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/logout()"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s7CVarArgP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegate":{"role":"symbol","title":"FTURLSessionDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegate"}],"abstract":[{"type":"codeVoice","code":"URLSession"},{"type":"text","text":" 支持自动化采集的代理委托对象。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegate"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/logging(_:status:)":{"role":"symbol","title":"logging(_:status:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTLogStatus","preciseIdentifier":"c:@E@FTLogStatus"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"添加自定义日志"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logging(_:status:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logging:status:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/logging(_:status:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/sharedInstance()":{"role":"symbol","title":"sharedInstance()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"返回之前所初始化好的单例."},{"type":"text","text":" "},{"type":"text","text":"调用这个方法之前，必须先调用 startWithConfigOptions 这个方法"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/sharedInstance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/sharedinstance()"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/logging(_:status:property:)":{"role":"symbol","title":"logging(_:status:property:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logging"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTLogStatus","preciseIdentifier":"c:@E@FTLogStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"property"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"添加自定义日志"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logging(_:status:property:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logging:status:property:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/logging(_:status:property:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/startLogger(withConfigOptions:)":{"role":"symbol","title":"startLogger(withConfigOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLogger"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTLoggerConfig","preciseIdentifier":"c:objc(cs)FTLoggerConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"配置 Logger Config 开启 Logger 功能"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startLogger(withConfigOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLoggerWithConfigOptions:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/startlogger(withconfigoptions:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileConfig":{"role":"symbol","title":"FTMobileConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileConfig"}],"abstract":[{"type":"text","text":"SDK 基础配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileConfig"}],"url":"\/documentation\/ftmobileagent\/ftmobileconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager":{"role":"symbol","title":"FTExternalDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTExternalDataManager"}],"abstract":[{"type":"text","text":"实现用户自定义 RUM、 Trace 功能的类"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTExternalDataManager"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/isIntakeUrl(_:)":{"role":"symbol","title":"isIntakeUrl(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isIntakeUrl"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"设置过滤 Trace Resource 域名"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/isIntakeUrl(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isIntakeUrl:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/isintakeurl(_:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s28CustomDebugStringConvertibleP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLoggerConfig":{"role":"symbol","title":"FTLoggerConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLoggerConfig"}],"abstract":[{"type":"text","text":"logger 功能配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLoggerConfig"}],"url":"\/documentation\/ftmobileagent\/ftloggerconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/trackEventFromExtension(withGroupIdentifier:completion:)":{"role":"symbol","title":"trackEventFromExtension(withGroupIdentifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEventFromExtension"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withGroupIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Track App Extension groupIdentifier 中缓存的数据"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/trackEventFromExtension(withGroupIdentifier:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackEventFromExtensionWithGroupIdentifier:completion:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/trackeventfromextension(withgroupidentifier:completion:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig":{"role":"symbol","title":"FTRumConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"abstract":[{"type":"text","text":"RUM 功能的配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTRumConfig"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/start(withConfigOptions:)":{"role":"symbol","title":"start(withConfigOptions:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTMobileConfig","preciseIdentifier":"c:objc(cs)FTMobileConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"SDK 初始化方法"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/start(withConfigOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithConfigOptions:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/start(withconfigoptions:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/startTrace(withConfigOptions:)":{"role":"symbol","title":"startTrace(withConfigOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startTrace"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTTraceConfig","preciseIdentifier":"c:objc(cs)FTTraceConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"配置 Trace Config 开启 Trace 功能"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startTrace(withConfigOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startTraceWithConfigOptions:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/starttrace(withconfigoptions:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s23CustomStringConvertibleP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/bindUser(withUserID:)":{"role":"symbol","title":"bindUser(withUserID:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withUserID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"绑定用户信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindUserWithUserID:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/binduser(withuserid:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent":{"role":"symbol","title":"FTMobileAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"abstract":[{"type":"text","text":"FTMobileSDK"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileAgent"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTTraceConfig":{"role":"symbol","title":"FTTraceConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTTraceConfig"}],"abstract":[{"type":"text","text":"Trace 功能配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTTraceConfig"}],"url":"\/documentation\/ftmobileagent\/fttraceconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTTraceManager":{"role":"symbol","title":"FTTraceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTTraceManager"}],"abstract":[{"type":"text","text":"管理 trace 的类"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTTraceManager"}],"url":"\/documentation\/ftmobileagent\/fttracemanager"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/startRum(withConfigOptions:)":{"role":"symbol","title":"startRum(withConfigOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRum"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTRumConfig","preciseIdentifier":"c:objc(cs)FTRumConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"配置 RUM Config 开启 RUM 功能"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startRum(withConfigOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startRumWithConfigOptions:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/startrum(withconfigoptions:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/bindUser(withUserID:userName:userEmail:extra:)":{"role":"symbol","title":"bindUser(withUserID:userName:userEmail:extra:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withUserID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"extra"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"绑定用户信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:userName:userEmail:extra:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindUserWithUserID:userName:userEmail:extra:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/binduser(withuserid:username:useremail:extra:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/bindUser(withUserID:userName:userEmail:)":{"role":"symbol","title":"bindUser(withUserID:userName:userEmail:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withUserID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"userEmail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"绑定用户信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:userName:userEmail:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindUserWithUserID:userName:userEmail:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/binduser(withuserid:username:useremail:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FTMobileAgent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTMobileAgent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTMobileAgent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:userName:userEmail:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/bindUser(withUserID:userName:userEmail:extra:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/isIntakeUrl(_:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logging(_:status:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logging(_:status:property:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/logout()","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startLogger(withConfigOptions:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startRum(withConfigOptions:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startTrace(withConfigOptions:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/trackEventFromExtension(withGroupIdentifier:completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/sharedInstance()","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/start(withConfigOptions:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1logout()\/title","value":"logout"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1logout()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/title","value":"FTURLSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1logging(_:status:)\/title","value":"logging:status:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1logging(_:status:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logging:status:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1sharedInstance()\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1sharedInstance()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1logging(_:status:property:)\/title","value":"logging:status:property:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1logging(_:status:property:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logging:status:property:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startLogger(withConfigOptions:)\/title","value":"startLoggerWithConfigOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startLogger(withConfigOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLoggerWithConfigOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileConfig\/title","value":"FTMobileConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileConfig\/fragments","value":[{"kind":"identifier","text":"FTMobileConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/title","value":"FTExternalDataManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/fragments","value":[{"kind":"identifier","text":"FTExternalDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1isIntakeUrl(_:)\/title","value":"isIntakeUrl:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1isIntakeUrl(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isIntakeUrl:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/title","value":"FTLoggerConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/fragments","value":[{"kind":"identifier","text":"FTLoggerConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1trackEventFromExtension(withGroupIdentifier:completion:)\/title","value":"trackEventFromExtensionWithGroupIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1trackEventFromExtension(withGroupIdentifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackEventFromExtensionWithGroupIdentifier:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/title","value":"FTRumConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/fragments","value":[{"kind":"identifier","text":"FTRumConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1start(withConfigOptions:)\/title","value":"startWithConfigOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1start(withConfigOptions:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"startWithConfigOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startTrace(withConfigOptions:)\/title","value":"startTraceWithConfigOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startTrace(withConfigOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startTraceWithConfigOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1bindUser(withUserID:)\/title","value":"bindUserWithUserID:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1bindUser(withUserID:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindUserWithUserID:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/title","value":"FTMobileAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/fragments","value":[{"kind":"identifier","text":"FTMobileAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceConfig\/title","value":"FTTraceConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceConfig\/fragments","value":[{"kind":"identifier","text":"FTTraceConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceManager\/title","value":"FTTraceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceManager\/fragments","value":[{"kind":"identifier","text":"FTTraceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startRum(withConfigOptions:)\/title","value":"startRumWithConfigOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startRum(withConfigOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRumWithConfigOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1bindUser(withUserID:userName:userEmail:extra:)\/title","value":"bindUserWithUserID:userName:userEmail:extra:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1bindUser(withUserID:userName:userEmail:extra:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindUserWithUserID:userName:userEmail:extra:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1bindUser(withUserID:userName:userEmail:)\/title","value":"bindUserWithUserID:userName:userEmail:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1bindUser(withUserID:userName:userEmail:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindUserWithUserID:userName:userEmail:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}