{"seeAlsoSections":[{"title":"Model","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceContentModel"}],"title":"FTResourceContentModel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)FTResourceContentModel","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTResourceContentModel"}]},"abstract":[{"type":"text","text":"Resource 数据内容"}],"sections":[],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s7CVarArgP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s28CustomDebugStringConvertibleP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s23CustomStringConvertibleP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/error","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/errorMessage","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/httpMethod","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/httpStatusCode","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/requestHeader","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/responseBody","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/responseHeader","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/url"]}],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftresourcecontentmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftresourcecontentmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceContentModel"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/httpMethod":{"role":"symbol","title":"httpMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"http 方法"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/httpMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"httpMethod"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/httpmethod"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/url":{"role":"symbol","title":"url","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[{"type":"text","text":"请求 url"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/url","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"url"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/url"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/httpStatusCode":{"role":"symbol","title":"httpStatusCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"httpStatusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"请求结果状态码"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/httpStatusCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"httpStatusCode"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/httpstatuscode"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s28CustomDebugStringConvertibleP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/responseHeader":{"role":"symbol","title":"responseHeader","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseHeader"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"响应头"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/responseHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"responseHeader"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/responseheader"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel":{"role":"symbol","title":"FTResourceContentModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceContentModel"}],"abstract":[{"type":"text","text":"Resource 数据内容"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceContentModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceMetricsModel":{"role":"symbol","title":"FTResourceMetricsModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceMetricsModel"}],"abstract":[{"type":"text","text":"资源加载时间数据模型"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceMetricsModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcemetricsmodel"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s23CustomStringConvertibleP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/requestHeader":{"role":"symbol","title":"requestHeader","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestHeader"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"请求头"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/requestHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestHeader"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/requestheader"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/errorMessage":{"role":"symbol","title":"errorMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"请求错误信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/errorMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorMessage"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/errormessage"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/responseBody":{"role":"symbol","title":"responseBody","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseBody"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"响应结果"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/responseBody","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"responseBody"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/responsebody"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceContentModel/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[{"type":"text","text":"error 信息 （ios native）"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"error"}],"url":"\/documentation\/ftmobileagent\/ftresourcecontentmodel\/error"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FTResourceContentModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTResourceContentModel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTResourceContentModel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/error","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/errorMessage","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/httpMethod","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/httpStatusCode","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/requestHeader","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/responseBody","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/responseHeader","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceContentModel\/url"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Model","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceContentModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1httpMethod\/title","value":"httpMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1httpMethod\/fragments","value":[{"kind":"identifier","text":"httpMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1httpStatusCode\/title","value":"httpStatusCode"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1httpStatusCode\/fragments","value":[{"kind":"identifier","text":"httpStatusCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1responseHeader\/title","value":"responseHeader"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1responseHeader\/fragments","value":[{"kind":"identifier","text":"responseHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel\/title","value":"FTResourceContentModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel\/fragments","value":[{"kind":"identifier","text":"FTResourceContentModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/title","value":"FTResourceMetricsModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/fragments","value":[{"kind":"identifier","text":"FTResourceMetricsModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1requestHeader\/title","value":"requestHeader"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1requestHeader\/fragments","value":[{"kind":"identifier","text":"requestHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1errorMessage\/title","value":"errorMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1errorMessage\/fragments","value":[{"kind":"identifier","text":"errorMessage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1responseBody\/title","value":"responseBody"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1responseBody\/fragments","value":[{"kind":"identifier","text":"responseBody"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1error\/title","value":"error"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceContentModel~1error\/fragments","value":[{"kind":"identifier","text":"error"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}