{"seeAlsoSections":[{"title":"Classes","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"title":"FTRumConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)FTRumConfig","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTRumConfig"}]},"abstract":[{"type":"text","text":"RUM 功能的配置项"}],"sections":[],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s7CVarArgP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s28CustomDebugStringConvertibleP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s23CustomStringConvertibleP","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/init(appid:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/appid","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/deviceMetricsMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserAction","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserResource","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserView","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppANR","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppCrash","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppFreeze","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/errorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/globalContext","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/monitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/samplerate"]}],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftrumconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftrumconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/enableTraceUserResource":{"role":"symbol","title":"enableTraceUserResource","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTraceUserResource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"设置是否追踪用户网络请求  (仅作用于native http)"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserResource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableTraceUserResource"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/enabletraceuserresource"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s28CustomDebugStringConvertibleP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s7CVarArgP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/init(appid:)":{"role":"symbol","title":"init(appid:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"指定初始化方法，设置 appid"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/init(appid:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAppid:"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/init(appid:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLoggerConfig":{"role":"symbol","title":"FTLoggerConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLoggerConfig"}],"abstract":[{"type":"text","text":"logger 功能配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLoggerConfig"}],"url":"\/documentation\/ftmobileagent\/ftloggerconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/globalContext":{"role":"symbol","title":"globalContext","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"globalContext"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"设置 rum 全局 tag"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/globalContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"globalContext"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/globalcontext"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig":{"role":"symbol","title":"FTRumConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"abstract":[{"type":"text","text":"RUM 功能的配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTRumConfig"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SQ"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/deviceMetricsMonitorType":{"role":"symbol","title":"deviceMetricsMonitorType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceMetricsMonitorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTDeviceMetricsMonitorType","preciseIdentifier":"c:@E@FTDeviceMetricsMonitorType"}],"abstract":[{"type":"text","text":"设置监控类型 不设置则不开启监控"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/deviceMetricsMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceMetricsMonitorType"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/devicemetricsmonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/screenShotCompressionQuality":{"role":"symbol","title":"screenShotCompressionQuality","fragments":[{"kind":"identifier","text":"screenShotCompressionQuality"}],"abstract":[{"type":"text","text":"设置截图保存分辨率 范围0.25~1"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/screenShotCompressionQuality","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent\/ftrumconfig\/screenshotcompressionquality"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager":{"role":"symbol","title":"FTExternalDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTExternalDataManager"}],"abstract":[{"type":"text","text":"实现用户自定义 RUM、 Trace 功能的类"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTExternalDataManager"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/appid":{"role":"symbol","title":"appid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"应用唯一 ID，在 DataFlux 控制台上面创建监控时自动生成。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/appid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appid"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/appid"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/SH"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileConfig":{"role":"symbol","title":"FTMobileConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileConfig"}],"abstract":[{"type":"text","text":"SDK 基础配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileConfig"}],"url":"\/documentation\/ftmobileagent\/ftmobileconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/enableTraceUserAction":{"role":"symbol","title":"enableTraceUserAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTraceUserAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"设置是否追踪用户操作，目前支持应用启动和点击操作，"},{"type":"text","text":" "},{"type":"text","text":"在 enableTraceUserView 开启的状况下 开启才能生效（仅作用于autotrack）"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableTraceUserAction"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/enabletraceuseraction"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/enableTrackAppANR":{"role":"symbol","title":"enableTrackAppANR","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTrackAppANR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"设置是否需要采集 ANR"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppANR","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableTrackAppANR"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/enabletrackappanr"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTTraceConfig":{"role":"symbol","title":"FTTraceConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTTraceConfig"}],"abstract":[{"type":"text","text":"Trace 功能配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTTraceConfig"}],"url":"\/documentation\/ftmobileagent\/fttraceconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/monitorFrequency":{"role":"symbol","title":"monitorFrequency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"monitorFrequency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTMonitorFrequency","preciseIdentifier":"c:@E@FTMonitorFrequency"}],"abstract":[{"type":"text","text":"设置监控采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/monitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"monitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/monitorfrequency"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/enableScreenShot":{"role":"symbol","title":"enableScreenShot","fragments":[{"kind":"identifier","text":"enableScreenShot"}],"abstract":[{"type":"text","text":"允许开启截图功能"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableScreenShot","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent\/ftrumconfig\/enablescreenshot"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/enableTrackAppCrash":{"role":"symbol","title":"enableTrackAppCrash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTrackAppCrash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"设置是否需要采集崩溃日志"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppCrash","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableTrackAppCrash"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/enabletrackappcrash"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/enableTrackAppFreeze":{"role":"symbol","title":"enableTrackAppFreeze","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTrackAppFreeze"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"设置是否需要采集卡顿"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppFreeze","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableTrackAppFreeze"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/enabletrackappfreeze"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent":{"role":"symbol","title":"FTMobileAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"abstract":[{"type":"text","text":"FTMobileSDK"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileAgent"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/samplerate":{"role":"symbol","title":"samplerate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"samplerate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[{"type":"text","text":"采样配置，属性值：0至100，100则表示百分百采集，不做数据样本压缩。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/samplerate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"samplerate"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/samplerate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegate":{"role":"symbol","title":"FTURLSessionDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegate"}],"abstract":[{"type":"codeVoice","code":"URLSession"},{"type":"text","text":" 支持自动化采集的代理委托对象。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegate"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/enableTraceUserView":{"role":"symbol","title":"enableTraceUserView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"enableTraceUserView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"设置是否追踪页面生命周期 （仅作用于autotrack）"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enableTraceUserView"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/enabletraceuserview"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/s23CustomStringConvertibleP"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTTraceManager":{"role":"symbol","title":"FTTraceManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTTraceManager"}],"abstract":[{"type":"text","text":"管理 trace 的类"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTTraceManager"}],"url":"\/documentation\/ftmobileagent\/fttracemanager"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig/errorMonitorType":{"role":"symbol","title":"errorMonitorType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMonitorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTErrorMonitorType","preciseIdentifier":"c:@E@FTErrorMonitorType"}],"abstract":[{"type":"text","text":"ERROR 中的设备信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/errorMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorMonitorType"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig\/errormonitortype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FTRumConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTRumConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTRumConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/appid","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/deviceMetricsMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableScreenShot","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserAction","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserResource","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTraceUserView","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppANR","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppCrash","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/enableTrackAppFreeze","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/errorMonitorType","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/globalContext","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/monitorFrequency","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/samplerate","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/screenShotCompressionQuality"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig\/init(appid:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTTraceManager","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTraceUserResource\/title","value":"enableTraceUserResource"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTraceUserResource\/fragments","value":[{"kind":"identifier","text":"enableTraceUserResource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1init(appid:)\/title","value":"initWithAppid:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1init(appid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAppid:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/title","value":"FTLoggerConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/fragments","value":[{"kind":"identifier","text":"FTLoggerConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1globalContext\/title","value":"globalContext"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1globalContext\/fragments","value":[{"kind":"identifier","text":"globalContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/title","value":"FTRumConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/fragments","value":[{"kind":"identifier","text":"FTRumConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1deviceMetricsMonitorType\/title","value":"deviceMetricsMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1deviceMetricsMonitorType\/fragments","value":[{"kind":"identifier","text":"deviceMetricsMonitorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/title","value":"FTExternalDataManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/fragments","value":[{"kind":"identifier","text":"FTExternalDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1appid\/title","value":"appid"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1appid\/fragments","value":[{"kind":"identifier","text":"appid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileConfig\/title","value":"FTMobileConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileConfig\/fragments","value":[{"kind":"identifier","text":"FTMobileConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTraceUserAction\/title","value":"enableTraceUserAction"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTraceUserAction\/fragments","value":[{"kind":"identifier","text":"enableTraceUserAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTrackAppANR\/title","value":"enableTrackAppANR"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTrackAppANR\/fragments","value":[{"kind":"identifier","text":"enableTrackAppANR"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceConfig\/title","value":"FTTraceConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceConfig\/fragments","value":[{"kind":"identifier","text":"FTTraceConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1monitorFrequency\/title","value":"monitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1monitorFrequency\/fragments","value":[{"kind":"identifier","text":"monitorFrequency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTrackAppCrash\/title","value":"enableTrackAppCrash"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTrackAppCrash\/fragments","value":[{"kind":"identifier","text":"enableTrackAppCrash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTrackAppFreeze\/title","value":"enableTrackAppFreeze"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTrackAppFreeze\/fragments","value":[{"kind":"identifier","text":"enableTrackAppFreeze"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/title","value":"FTMobileAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/fragments","value":[{"kind":"identifier","text":"FTMobileAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1samplerate\/title","value":"samplerate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1samplerate\/fragments","value":[{"kind":"identifier","text":"samplerate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/title","value":"FTURLSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTraceUserView\/title","value":"enableTraceUserView"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1enableTraceUserView\/fragments","value":[{"kind":"identifier","text":"enableTraceUserView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceManager\/title","value":"FTTraceManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTTraceManager\/fragments","value":[{"kind":"identifier","text":"FTTraceManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1errorMonitorType\/title","value":"errorMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig~1errorMonitorType\/fragments","value":[{"kind":"identifier","text":"errorMonitorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}