{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegateProviding"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"URLSessionDelegate","preciseIdentifier":"c:objc(pl)NSURLSessionDelegate"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"必须确保 "},{"type":"codeVoice","code":"ftURLSessionDelegate"},{"type":"text","text":" 调用所需的方法"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/fturlsessiondelegateproviding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/fturlsessiondelegateproviding"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSURLSessionDelegate","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"转发 ‘URLSessionDelegate’ 调用到 ‘ftURLSessionDelegate’的接口协议。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegateProviding"}],"title":"FTURLSessionDelegateProviding","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)FTURLSessionDelegateProviding","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegateProviding"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding\/ftURLSessionDelegate"]}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegateProviding/ftURLSessionDelegate":{"navigatorTitle":[{"kind":"identifier","text":"ftURLSessionDelegate"}],"role":"symbol","title":"ftURLSessionDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ftURLSessionDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTURLSessionDelegate","preciseIdentifier":"c:objc(cs)FTURLSessionDelegate"}],"abstract":[{"type":"text","text":"自动化采集的委托代理对象"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding\/ftURLSessionDelegate","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/ftmobileagent\/fturlsessiondelegateproviding\/fturlsessiondelegate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegate":{"role":"symbol","title":"FTURLSessionDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegate"}],"abstract":[{"type":"codeVoice","code":"URLSession"},{"type":"text","text":" 支持自动化采集的代理委托对象。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegate"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSObject"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/objc(pl)NSURLSessionDelegate":{"type":"unresolvable","title":"NSURLSessionDelegate","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSURLSessionDelegate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegateProviding":{"role":"symbol","title":"FTURLSessionDelegateProviding","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegateProviding"}],"abstract":[{"type":"text","text":"转发 ‘URLSessionDelegate’ 调用到 ‘ftURLSessionDelegate’的接口协议。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegateProviding"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegateproviding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"FTURLSessionDelegateProviding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegateProviding"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FTURLSessionDelegateProviding"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegateProviding\/ftURLSessionDelegate"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/objc(pl)NSURLSessionDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegateProviding"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSURLSessionDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegateProviding~1ftURLSessionDelegate\/title","value":"ftURLSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegateProviding~1ftURLSessionDelegate\/fragments","value":[{"kind":"identifier","text":"ftURLSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/title","value":"FTURLSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegateProviding\/title","value":"FTURLSessionDelegateProviding"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegateProviding\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegateProviding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}