{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopView"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftexternaldatamanager\/stopview()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftexternaldatamanager\/stopview()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/stopView()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"离开页面"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopView"},{"kind":"text","text":"()"}],"title":"stopView()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FTExternalDataManager(im)stopView","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"stopView"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager/stopView()":{"role":"symbol","title":"stopView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopView"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"离开页面"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/stopView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopView"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager\/stopview()"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager":{"role":"symbol","title":"FTExternalDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTExternalDataManager"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTExternalDataManager"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stopView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1stopView()\/title","value":"stopView"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1stopView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/title","value":"FTExternalDataManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/fragments","value":[{"kind":"identifier","text":"FTExternalDataManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}