{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCreateView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"页面名称"}]}]},{"name":"loadTime","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"页面加载时间"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"在 "},{"type":"codeVoice","code":"-startViewWithName"},{"type":"text","text":" 方法前调用，该方法用于记录页面的加载时间，如果无法获得加载时间该方法可以不调用。"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftexternaldatamanager\/oncreateview(_:loadtime:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftexternaldatamanager\/oncreateview(_:loadtime:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/onCreateView(_:loadTime:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"创建页面"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCreateView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"title":"onCreateView(_:loadTime:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FTExternalDataManager(im)onCreateView:loadTime:","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"onCreateView:loadTime:"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager"]]},"seeAlsoSections":[{"title":"View","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/startView(withName:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/stopView()"],"generated":true}],"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager/startView(withName:)":{"role":"symbol","title":"startView(withName:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"进入页面"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/startView(withName:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startViewWithName:"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager\/startview(withname:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager":{"role":"symbol","title":"FTExternalDataManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTExternalDataManager"}],"abstract":[{"type":"text","text":"实现用户自定义 RUM、 Trace 功能的类"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTExternalDataManager"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager/onCreateView(_:loadTime:)":{"role":"symbol","title":"onCreateView(_:loadTime:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCreateView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loadTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"创建页面"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/onCreateView(_:loadTime:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCreateView:loadTime:"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager\/oncreateview(_:loadtime:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTExternalDataManager/stopView()":{"role":"symbol","title":"stopView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopView"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"离开页面"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/stopView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopView"}],"url":"\/documentation\/ftmobileagent\/ftexternaldatamanager\/stopview()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onCreateView:loadTime:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCreateView:loadTime:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"View","identifiers":["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/startView(withName:)","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTExternalDataManager\/stopView()"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onCreateView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewName"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadTime:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"loadTime"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1startView(withName:)\/title","value":"startViewWithName:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1startView(withName:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startViewWithName:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/title","value":"FTExternalDataManager"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager\/fragments","value":[{"kind":"identifier","text":"FTExternalDataManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1onCreateView(_:loadTime:)\/title","value":"onCreateView:loadTime:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1onCreateView(_:loadTime:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCreateView:loadTime:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1stopView()\/title","value":"stopView"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTExternalDataManager~1stopView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}