{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","preciseIdentifier":"c:@E@FTErrorMonitorType","text":"FTErrorMonitorType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/fterrormonitortype\/cpu"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/fterrormonitortype\/cpu"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType\/cpu","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"CPU使用率"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTErrorMonitorType","preciseIdentifier":"c:@E@FTErrorMonitorType"}],"title":"cpu","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@FTErrorMonitorType@FTErrorMonitorCpu","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTErrorMonitorCpu"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTErrorMonitorType/cpu":{"role":"symbol","title":"cpu","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cpu"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTErrorMonitorType","preciseIdentifier":"c:@E@FTErrorMonitorType"}],"abstract":[{"type":"text","text":"CPU使用率"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType\/cpu","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTErrorMonitorCpu"}],"url":"\/documentation\/ftmobileagent\/fterrormonitortype\/cpu"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTErrorMonitorType":{"role":"symbol","title":"FTErrorMonitorType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTErrorMonitorType"}],"abstract":[{"type":"text","text":"ERROR 中的设备信息"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTErrorMonitorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTErrorMonitorType"}],"url":"\/documentation\/ftmobileagent\/fterrormonitortype"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FTErrorMonitorCpu"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTErrorMonitorCpu"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FTErrorMonitorCpu"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType~1cpu\/title","value":"FTErrorMonitorCpu"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType~1cpu\/fragments","value":[{"kind":"identifier","text":"FTErrorMonitorCpu"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/title","value":"FTErrorMonitorType"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTErrorMonitorType\/fragments","value":[{"kind":"identifier","text":"FTErrorMonitorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}