{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRum"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rumConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","preciseIdentifier":"c:objc(cs)FTRumConfig","text":"FTRumConfig"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"rumConfigOptions","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"rum 配置项."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"RUM 用户监测，采集用户的行为数据，支持采集 View、Action、Resource、LongTask、Error。支持自动采集和手动添加。"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftmobileagent\/startrum(withconfigoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftmobileagent\/startrum(withconfigoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startRum(withConfigOptions:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"配置 RUM Config 开启 RUM 功能"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRum"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTRumConfig","preciseIdentifier":"c:objc(cs)FTRumConfig"},{"kind":"text","text":")"}],"title":"startRum(withConfigOptions:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FTMobileAgent(im)startRumWithConfigOptions:","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"startRumWithConfigOptions:"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/startRum(withConfigOptions:)":{"role":"symbol","title":"startRum(withConfigOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startRum"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTRumConfig","preciseIdentifier":"c:objc(cs)FTRumConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"配置 RUM Config 开启 RUM 功能"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startRum(withConfigOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startRumWithConfigOptions:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/startrum(withconfigoptions:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent":{"role":"symbol","title":"FTMobileAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileAgent"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTRumConfig":{"role":"symbol","title":"FTRumConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTRumConfig"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTRumConfig"}],"url":"\/documentation\/ftmobileagent\/ftrumconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startRumWithConfigOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRumWithConfigOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startRumWithConfigOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTRumConfig","preciseIdentifier":"c:objc(cs)FTRumConfig","text":"FTRumConfig"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"rumConfigOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startRum(withConfigOptions:)\/title","value":"startRumWithConfigOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startRum(withConfigOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRumWithConfigOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/title","value":"FTMobileAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/fragments","value":[{"kind":"identifier","text":"FTMobileAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/title","value":"FTRumConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTRumConfig\/fragments","value":[{"kind":"identifier","text":"FTRumConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}