{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLogger"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":" "},{"kind":"internalParam","text":"loggerConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","preciseIdentifier":"c:objc(cs)FTLoggerConfig","text":"FTLoggerConfig"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"loggerConfigOptions","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"logger 配置项."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftmobileagent\/startlogger(withconfigoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftmobileagent\/startlogger(withconfigoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startLogger(withConfigOptions:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"配置 Logger Config 开启 Logger 功能"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLogger"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTLoggerConfig","preciseIdentifier":"c:objc(cs)FTLoggerConfig"},{"kind":"text","text":")"}],"title":"startLogger(withConfigOptions:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FTMobileAgent(im)startLoggerWithConfigOptions:","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"startLoggerWithConfigOptions:"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTLoggerConfig":{"role":"symbol","title":"FTLoggerConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTLoggerConfig"}],"abstract":[{"type":"text","text":"logger 功能配置项"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTLoggerConfig"}],"url":"\/documentation\/ftmobileagent\/ftloggerconfig"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent":{"role":"symbol","title":"FTMobileAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"abstract":[{"type":"text","text":"FTMobileSDK"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileAgent"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/startLogger(withConfigOptions:)":{"role":"symbol","title":"startLogger(withConfigOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLogger"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FTLoggerConfig","preciseIdentifier":"c:objc(cs)FTLoggerConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"配置 Logger Config 开启 Logger 功能"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/startLogger(withConfigOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startLoggerWithConfigOptions:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/startlogger(withconfigoptions:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"startLoggerWithConfigOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLoggerWithConfigOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"startLoggerWithConfigOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTLoggerConfig","preciseIdentifier":"c:objc(cs)FTLoggerConfig","text":"FTLoggerConfig"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"loggerConfigOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/title","value":"FTLoggerConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTLoggerConfig\/fragments","value":[{"kind":"identifier","text":"FTLoggerConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/title","value":"FTMobileAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/fragments","value":[{"kind":"identifier","text":"FTMobileAgent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startLogger(withConfigOptions:)\/title","value":"startLoggerWithConfigOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1startLogger(withConfigOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startLoggerWithConfigOptions:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}