{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEventFromExtension"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withGroupIdentifier"},{"kind":"text","text":" "},{"kind":"internalParam","text":"groupIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"groupIdentifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"groupIdentifier"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"完成 track 后的 callback"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftmobileagent\/trackeventfromextension(withgroupidentifier:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftmobileagent\/trackeventfromextension(withgroupidentifier:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/trackEventFromExtension(withGroupIdentifier:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Track App Extension groupIdentifier 中缓存的数据"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEventFromExtension"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withGroupIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"title":"trackEventFromExtension(withGroupIdentifier:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FTMobileAgent(im)trackEventFromExtensionWithGroupIdentifier:completion:","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"trackEventFromExtensionWithGroupIdentifier:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent/trackEventFromExtension(withGroupIdentifier:completion:)":{"role":"symbol","title":"trackEventFromExtension(withGroupIdentifier:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackEventFromExtension"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withGroupIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Track App Extension groupIdentifier 中缓存的数据"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent\/trackEventFromExtension(withGroupIdentifier:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackEventFromExtensionWithGroupIdentifier:completion:"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent\/trackeventfromextension(withgroupidentifier:completion:)"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMobileAgent":{"role":"symbol","title":"FTMobileAgent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMobileAgent"}],"abstract":[{"type":"text","text":"FTMobileSDK"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMobileAgent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMobileAgent"}],"url":"\/documentation\/ftmobileagent\/ftmobileagent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"trackEventFromExtensionWithGroupIdentifier:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackEventFromExtensionWithGroupIdentifier:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"trackEventFromExtensionWithGroupIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"groupIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSString *, NSArray *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#*$objc(cs)NSArray)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1trackEventFromExtension(withGroupIdentifier:completion:)\/title","value":"trackEventFromExtensionWithGroupIdentifier:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent~1trackEventFromExtension(withGroupIdentifier:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"trackEventFromExtensionWithGroupIdentifier:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/title","value":"FTMobileAgent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMobileAgent\/fragments","value":[{"kind":"identifier","text":"FTMobileAgent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}