{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resource_ttfb"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftresourcemetricsmodel\/resource_ttfb"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftresourcemetricsmodel\/resource_ttfb"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel\/resource_ttfb","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"资源加载请求响应时间 responseStart - requestStart"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resource_ttfb"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"title":"resource_ttfb","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)FTResourceMetricsModel(py)resource_ttfb","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"resource_ttfb"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceMetricsModel":{"role":"symbol","title":"FTResourceMetricsModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTResourceMetricsModel"}],"abstract":[],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTResourceMetricsModel"}],"url":"\/documentation\/ftmobileagent\/ftresourcemetricsmodel"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTResourceMetricsModel/resource_ttfb":{"role":"symbol","title":"resource_ttfb","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resource_ttfb"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"abstract":[{"type":"text","text":"资源加载请求响应时间 responseStart - requestStart"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTResourceMetricsModel\/resource_ttfb","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resource_ttfb"}],"url":"\/documentation\/ftmobileagent\/ftresourcemetricsmodel\/resource_ttfb"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"resource_ttfb"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"resource_ttfb"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"resource_ttfb"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/title","value":"FTResourceMetricsModel"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel\/fragments","value":[{"kind":"identifier","text":"FTResourceMetricsModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel~1resource_ttfb\/title","value":"resource_ttfb"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTResourceMetricsModel~1resource_ttfb\/fragments","value":[{"kind":"identifier","text":"resource_ttfb"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}