{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ftURLSessionDelegate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate","preciseIdentifier":"c:objc(cs)FTURLSessionDelegate","text":"FTURLSessionDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/fturlsessiondelegate\/fturlsessiondelegate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/fturlsessiondelegate\/fturlsessiondelegate()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate\/ftURLSessionDelegate()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"实现拦截 url 请求过程的代理"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ftURLSessionDelegate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"FTURLSessionDelegate","preciseIdentifier":"c:objc(cs)FTURLSessionDelegate"}],"title":"ftURLSessionDelegate()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)FTURLSessionDelegate(im)ftURLSessionDelegate","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"ftURLSessionDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegate":{"role":"symbol","title":"FTURLSessionDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTURLSessionDelegate"}],"abstract":[{"type":"codeVoice","code":"URLSession"},{"type":"text","text":" 支持自动化采集的代理委托对象。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTURLSessionDelegate"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegate"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTURLSessionDelegate/ftURLSessionDelegate()":{"role":"symbol","title":"ftURLSessionDelegate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ftURLSessionDelegate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"FTURLSessionDelegate","preciseIdentifier":"c:objc(cs)FTURLSessionDelegate"}],"abstract":[{"type":"text","text":"实现拦截 url 请求过程的代理"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate\/ftURLSessionDelegate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ftURLSessionDelegate"}],"url":"\/documentation\/ftmobileagent\/fturlsessiondelegate\/fturlsessiondelegate()"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"ftURLSessionDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ftURLSessionDelegate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTURLSessionDelegate","preciseIdentifier":"c:objc(cs)FTURLSessionDelegate","text":"FTURLSessionDelegate"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"ftURLSessionDelegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/title","value":"FTURLSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate\/fragments","value":[{"kind":"identifier","text":"FTURLSessionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate~1ftURLSessionDelegate()\/title","value":"ftURLSessionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTURLSessionDelegate~1ftURLSessionDelegate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"ftURLSessionDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}