{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"frequent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftmonitorfrequency\/frequent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftmonitorfrequency\/frequent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency\/frequent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"100ms"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"frequent"}],"title":"FTMonitorFrequency.frequent","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@FTMonitorFrequency@FTMonitorFrequencyFrequent","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequencyFrequent"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency/frequent":{"role":"symbol","title":"FTMonitorFrequency.frequent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"frequent"}],"abstract":[{"type":"text","text":"100ms"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency\/frequent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequencyFrequent"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency\/frequent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency":{"role":"symbol","title":"FTMonitorFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMonitorFrequency"}],"abstract":[{"type":"text","text":"监控项采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FTMonitorFrequencyFrequent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequencyFrequent"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FTMonitorFrequencyFrequent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency~1frequent\/title","value":"FTMonitorFrequencyFrequent"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency~1frequent\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequencyFrequent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/title","value":"FTMonitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}