{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rare"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ftmobileagent\/ftmonitorfrequency\/rare"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/ftmobileagent\/ftmonitorfrequency\/rare"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency\/rare","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1000ms"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rare"}],"title":"FTMonitorFrequency.rare","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@FTMonitorFrequency@FTMonitorFrequencyRare","modules":[{"name":"FTMobileAgent"}],"navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequencyRare"}]},"hierarchy":{"paths":[["doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency"]]},"references":{"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent":{"role":"collection","title":"FTMobileAgent","abstract":[{"type":"text","text":"用于收集 iOS 应用的指标数据，用于 “观测云” 应用监测功能，以可视化的方式分析各个iOS应用端的性能。"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent","kind":"symbol","type":"topic","url":"\/documentation\/ftmobileagent"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency/rare":{"role":"symbol","title":"FTMonitorFrequency.rare","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rare"}],"abstract":[{"type":"text","text":"1000ms"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency\/rare","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequencyRare"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency\/rare"},"doc://com.cloudcare.ft.mobile.sdk.FTMobileAgent/documentation/FTMobileAgent/FTMonitorFrequency":{"role":"symbol","title":"FTMonitorFrequency","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FTMonitorFrequency"}],"abstract":[{"type":"text","text":"监控项采样周期"}],"identifier":"doc:\/\/com.cloudcare.ft.mobile.sdk.FTMobileAgent\/documentation\/FTMobileAgent\/FTMonitorFrequency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FTMonitorFrequency"}],"url":"\/documentation\/ftmobileagent\/ftmonitorfrequency"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FTMonitorFrequencyRare"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequencyRare"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FTMonitorFrequencyRare"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency~1rare\/title","value":"FTMonitorFrequencyRare"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency~1rare\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequencyRare"}]},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/title","value":"FTMonitorFrequency"},{"op":"replace","path":"\/references\/doc:~1~1com.cloudcare.ft.mobile.sdk.FTMobileAgent~1documentation~1FTMobileAgent~1FTMonitorFrequency\/fragments","value":[{"kind":"identifier","text":"FTMonitorFrequency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}